data:
    sample:
        shuffle : True
        random_state : 42
        train_size : 800
        stratify : True
    add_noise:
        train_noise : 1
        time_series : True
    name: classification
    files:
        data_path : data
        data_filetype : pickle
    generate:
        n_samples: 1000
        n_features: 2
        n_informative: 2
        n_redundant : 0
        n_classes: 2
    sklearn_pipeline:
        transform:
            name : sklearn.preprocessing.StandardScaler
            with_mean : true
            with_std : true
            X_train : true
            X_test : true
