stages:
  prepare:
    cmd: 
      - python ../../deckard/layers/prepare.py  -d 'data.csv'
    deps: 
      - configs/prepare.yml
      - ../../deckard/base/data.py
      - data.csv
    outs: 
      - data/data.pkl
  train:
    cmd: python ../../deckard/layers/train.py  -f data -s f1 -b  True --name train
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yml
    - ../../deckard/layers/train.py
    - ../../deckard/base/experiment.py
    - data/data.pkl
    outs:
    - data/train/model
    - data/train/data_params.json:
        cache: true
    - data/train/model_params.json:
        cache: true
    metrics:
    - data/train/scores.json:
        cache: true
    
  preprocess:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s f1 -b True --name preprocess --input train
    deps:
    - configs/preprocess.yml
    - ../../deckard/layers/preprocess.py
    - data/train/model
    outs:
    - data/preprocess/model
    - data/preprocess/data_params.json:
        cache: true
    - data/preprocess/model_params.json:
        cache: true
    metrics:
    - data/preprocess/scores.json:
        cache: true
   
  featurize:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s f1 -b True --name featurize --input preprocess
    deps:
    - configs/featurize.yml
    - ../../deckard/layers/preprocess.py
    - data/preprocess/model
    outs:
    - data/featurize/model
    - data/featurize/data_params.json:
        cache: true
    - data/featurize/model_params.json:
        cache: true
    metrics:
    - data/featurize/scores.json:
        cache: true


