stages:
  prepare:
    cmd: 
      - python -m deckard.layers.prepare  -d 'data.csv'
    deps: 
      - configs/prepare.yml
      - data.csv
    outs: 
      - data/data.pkl
  train:
    cmd: python -m deckard.layers.train  -f data -b  True --name train
    deps:
    - configs/model.yml
    - data/data.pkl
    outs:
    - data/train/model
    - data/train/data_params.json:
        cache: true
    - data/train/model_params.json:
        cache: true
    metrics:
    - data/train/scores.json:
        cache: true
    
  preprocess:
    cmd: python -m deckard.layers.preprocess  -f data -b True --name preprocess --input train
    deps:
    - configs/preprocess.yml
    - data/train/model
    outs:
    - data/preprocess/model
    - data/preprocess/data_params.json:
        cache: true
    - data/preprocess/model_params.json:
        cache: true
    metrics:
    - data/preprocess/scores.json:
        cache: true
   
  featurize:
    cmd: python -m deckard.layers.preprocess  -f data -b True --name featurize --input preprocess
    deps:
    - configs/featurize.yml
    - data/preprocess/model.pickle
    outs:
    - data/featurize/model.pickle
    - data/featurize/data_params.json:
        cache: true
    - data/featurize/model_params.json:
        cache: true
    metrics:
    - data/featurize/scores.json:
        cache: true


