stages:
  prepare:
    cmd: 
      - python ../../deckard/layers/prepare.py  -d 'data.csv'
    deps: 
      - configs/prepare.yml
      - ../../deckard/base/data.py
      - data.csv
    outs: 
      - data/data.pkl
  train:
    cmd: python ../../deckard/layers/train.py  -f data -s f1 -b  True
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yml
    - ../../deckard/layers/train.py
    - ../../deckard/base/experiment.py
    - data/data.pkl
    outs:
    - data/best_train/model.pkl
    - data/best_train/data_params.json:
        cache: true
    - data/best_train/model_params.json:
        cache: true
    metrics:
    - data/best_train/results.json:
        cache: true
    
  preprocess:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s f1 -b True --name preprocess --experiment best_train
    deps:
    - configs/preprocess.yml
    - ../../deckard/layers/preprocess.py
    - data/best_train/model.pkl
    outs:
    - data/best_preprocess/model.pkl
    - data/best_preprocess/data_params.json:
        cache: true
    - data/best_preprocess/model_params.json:
        cache: true
    metrics:
    - data/best_preprocess/results.json:
        cache: true
   
  featurize:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s f1 -b True --name featurize --experiment best_preprocess
    deps:
    - configs/featurize.yml
    - ../../deckard/layers/preprocess.py
    - data/best_preprocess/model.pkl
    outs:
    - data/best_featurize/model.pkl
    - data/best_featurize/data_params.json:
        cache: true
    - data/best_featurize/model_params.json:
        cache: true
    metrics:
    - data/best_featurize/results.json:
        cache: true
  evaluate:
    cmd: 


