vars:
  - ../config/plots.yaml:line_plot
  - ../config/plots.yaml:scatter_plot
  # - ../config/plots.yaml:cat_plot
  - ../config/compile.yaml:attacks
  - ../config/compile.yaml:defences
  - ../config/compile.yaml:params
  - ../config/compile.yaml:fillna
stages:
  # compile:
  #   foreach: # iterates through each stage
  #     - mnist
  #     - cifar
  #     - cifar100
  #     - bit_depth/mnist/
  #     - bit_depth/cifar/
  #     - bit_depth/cifar100/
  #   do:
  #     cmd: python -m deckard.layers.compile --report_folder /result/${item}/reports/attack/ --results_file raw.csv --results_folder data/${item} --config "../config/compile.yaml"
  #     deps:
  #      - /result/${item}/reports/attack/
  #     outs:
  #     - data/${item}/raw.csv
  # get_power_data:
  #   foreach:
  #     - mnist
  #     - cifar
  #     - cifar100
  #     - bit_depth/mnist/
  #     - bit_depth/cifar/
  #     - bit_depth/cifar100/
  #   do:
  #     cmd: python -m deckard.layers.query_kepler --input_file data/${item}/raw.csv --output_file data/${item}/power.csv
  #     deps:
  #       -  data/bit_depth/${item}/raw.csv
  #       -  data/${item}/raw.csv
  #     outs:
  #       - data/${item}/power.csv
  clean:
    foreach:
      - mnist
      - cifar
      - cifar100
    do:
      cmd: python -m deckard.layers.clean_data --i data/${item}/power.csv --o ${item}/clean.csv --config "../config/compile.yaml"
      deps:
        - data/${item}/power.csv
        - ../config/compile.yaml
      outs:
        - ${item}/clean.csv
      params:
        - ../config/compile.yaml:
          - attacks
          - defences
          - params
          - fillna
  lifelines:
    foreach:
       - mnist
       - cifar
       - cifar100
    do:
      cmd: >-
        deckard survival
        --config-dir ../config
        --config-name lifelines.yaml
        ++data.name=${item}/clean.csv
        ++data.target=adv_failures
        target=adv_failures
        event_col=adv_failures
        duration_col=adv_fit_time
        dataset=${item}
        plots_folder=${item}
        model=weibull
      deps:
        - ${item}/clean.csv
        - ../config/lifelines.yaml
      plots:
        - ${item}/weibull_aft.pdf
        - ${item}/weibull_qq.pdf
        - ${item}/weibull_summary_plot.pdf
      metrics:
        - ${item}/aft_comparison.csv
      outs:
        - ${item}/weibull_summary.csv

  copy:
    foreach:
      - mnist
      - cifar
      - cifar100
    do:
      cmd: >-
        rm -rf ~/kepler-ml/plots/${item}/ && mkdir -p ~/kepler-ml/plots/${item}/ && cp -r ${item}/* ~/kepler-ml/plots/${item}/
      deps:
        - ${item}/
