defaults:
    - art : default
data:  ${data}
init:
    _target_: deckard.base.model.ModelInitializer
    name : torch_example.ResNet18
    num_channels: 3
    num_classes: 100
_target_: deckard.base.model.Model
trainer:
    np_epochs: 1
    batch_size: 1024
library : pytorch
