defaults:
    - _self_
    - data: torch_cifar100
    - model: torch_cifar100
    - attack: default
    - files: cifar100
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : grid
    - override hydra/launcher : joblib
def_name : control
atk_name : hsj
dataset : cifar100
model_name : ResNet18
device_id : gpu
stage : '???'
direction : 
  -  "maximize"
_target_ : deckard.base.experiment.Experiment
optimizers : 
  - accuracy
hydra:
  run:
    dir: ${files.directory}/logs/${stage}/
  sweep:
    dir: ${files.directory}/logs/${stage}/${model_name}
    subdir : ${def_name}/${atk_name}/${hydra.job.num}
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    direction: ${direction}
    study_name: ${def_name}_${atk_name}
    storage: sqlite:///${dataset}.db
    n_jobs: ???
    n_trials : 128
    max_failure_rate: 1.0
    params:
      ++model.art.initialize.optimizer.lr: choice( 0.1, 0.01, 0.001, .0001, .00001, 0.000001)
      ++model.trainer.nb_epoch: 20
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: ${hydra.sweeper.n_jobs}
    prefer : processes
    verbose: 10
    timeout: null
    pre_dispatch: n_jobs
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
