"""Scoring configuration exports and Hydra registrations."""

from .base import (  # noqa: F401
    DefaultClassifierConfig,
    DefaultRegressorConfig,
    ScorerConfig,
    ScorerDictConfig,
    build_scorer,
    build_scorer_dict,
    safe_store,
)

from .fairness import (  # noqa: E402
    DefaultFairlearnClassificationConfig,
    DefaultFairlearnConfig,
    DefaultFairlearnRegressionConfig,
    FairlearnScoreDictConfig,
    fairness_demographic_parity_difference,
    fairness_equalized_odds_difference,
    fairness_group_mae_difference,
    fairness_group_mean_prediction_difference,
    fairness_group_mse_difference,
)
from .survival import (  # noqa: E402
    DefaultLifelinesConfig,
    survival_aic_score,
    survival_bic_score,
    survival_concordance_score,
)
from .attack import (  # noqa: E402
    AttackScorerConfig,
    DefaultEvasionAttackScorerConfig,
    DefaultEvasionRegressionAttackScorerConfig,
    DefaultMembershipInferenceAttackScorerConfig,
    DefaultAttributeInferenceAttackScorerConfig,
    DefaultAttributeInferenceRegressionAttackScorerConfig,
)
from .data import (  # noqa: E402
    DefaultDataClassificationConfig,
    DefaultDataRegressionConfig,
    data_num_classes_score,
    data_class_count_min_score,
    data_class_count_max_score,
    data_class_imbalance_ratio_score,
    data_mutual_information_mean_score,
    data_mutual_information_max_score,
    data_empirical_cdf_function_score,
)
from .declarations import (  # noqa: E402
    DefaultClassifierDict,
    DefaultDataClassificationDict,
    DefaultDataRegressionDict,
    DefaultFairlearnClassificationDict,
    DefaultFairlearnDict,
    DefaultFairlearnRegressionDict,
    DefaultLifelinesDict,
    DefaultRegressorDict,
)


__all__ = [
    "ScorerConfig",
    "ScorerDictConfig",
    "DefaultClassifierConfig",
    "DefaultRegressorConfig",
    "DefaultFairlearnClassificationConfig",
    "DefaultFairlearnConfig",
    "DefaultFairlearnRegressionConfig",
    "FairlearnScoreDictConfig",
    "DefaultLifelinesConfig",
    "AttackScorerConfig",
    "DefaultEvasionAttackScorerConfig",
    "DefaultEvasionRegressionAttackScorerConfig",
    "DefaultMembershipInferenceAttackScorerConfig",
    "DefaultAttributeInferenceAttackScorerConfig",
    "DefaultAttributeInferenceRegressionAttackScorerConfig",
    "DefaultClassifierDict",
    "DefaultRegressorDict",
    "DefaultFairlearnDict",
    "DefaultFairlearnClassificationDict",
    "DefaultFairlearnRegressionDict",
    "DefaultLifelinesDict",
    "DefaultDataClassificationConfig",
    "DefaultDataRegressionConfig",
    "DefaultDataClassificationDict",
    "DefaultDataRegressionDict",
    "data_num_classes_score",
    "data_class_count_min_score",
    "data_class_count_max_score",
    "data_class_imbalance_ratio_score",
    "data_mutual_information_mean_score",
    "data_mutual_information_max_score",
    "data_empirical_cdf_function_score",
    "build_scorer",
    "build_scorer_dict",
    "survival_concordance_score",
    "survival_aic_score",
    "survival_bic_score",
    "fairness_demographic_parity_difference",
    "fairness_equalized_odds_difference",
    "fairness_group_mean_prediction_difference",
    "fairness_group_mae_difference",
    "fairness_group_mse_difference",
]
