_target_: deckard.score.anjana.DefaultAnjanaScorerConfig
scorers:
  k_anonymity:
    score_function: deckard.score.anjana.anjana_k_anonymity_score
  l_diversity:
    score_function: deckard.score.anjana.anjana_l_diversity_score
  t_closeness:
    score_function: deckard.score.anjana.anjana_t_closeness_score
