_target_: deckard.score.data.DefaultDataRegressionConfig
scorers:
  mutual_information_mean:
    score_function: deckard.score.data.data_mutual_information_mean_score
  mutual_information_max:
    score_function: deckard.score.data.data_mutual_information_max_score
  empirical_cdf:
    score_function: deckard.score.data.data_empirical_cdf_function_score
