defaults:
  - _self_
  - data: torch_mnist
  - model: torch_mnist
  - files: default
  - scorers: default
  - stage : null
  - params/model : null
  - params/attack : null
++data.sample.random_state: choice(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
++model.art.initialize.optimizer.lr: choice(10, 1, 0.1, 0.01, 0.001, 0.0001, 0.00001, 0.000001)
