stages:
  data:
    cmd: python -m deckard.layers.runner --stage data
    outs:
    - ${files.data_file}
    params:
    - data
    - files
    deps:
    - params.yaml
  model:
    cmd: python -m deckard.layers.runner --stage model
    outs:
    - ${files.reports}/model/${files.path}/${files.predictions_file}
    - ${files.reports}/model/${files.path}/${files.ground_truth_file}
    deps:
    - ${files.data_file}
    - params.yaml
    metrics:
    - ${files.reports}/model/${files.path}/scores.json
    params:
    - data
    - model
    - files
    - scorers
  attack:
    cmd: python -m deckard.layers.runner --stage attack
    outs:
    - ${files.reports}/attack/${files.path}/${files.predictions_file}
    - ${files.reports}/attack/${files.path}/${files.ground_truth_file}
    deps:
    - ${files.data_file}
    - ${files.reports}/model/${files.path}/${files.predictions_file}
    - ${files.reports}/model/${files.path}/${files.ground_truth_file}
    metrics:
    - ${files.reports}/attack/${files.path}/scores.json
    params:
    - data
    - model
    - attack
    - files
    - scorers

