reports: reports
data_dir: data
data_file : ${dataset}-${data.sample.random_state}-${data.sample.train_size}-${data.sample.test_size}
data_type: .pkl
model_dir : model
directory: ${dataset}
score_dict_file: score_dict.json
params_file : params.yaml
predictions_file : predictions.json
name : default
