
model_search:
  ++model.defense.defense_type: art.defences.preprocessor.CutMix
  ++model.defense.defense_params.alpha: range(0.1, 5.0, 0.5)
  ++model.defense.defense_params.probability: range(0.1, 1.0, 0.1)