# @package _global_
hydra:
  sweeper:
    params: 
      ++defense.defense_name: art.defences.postprocessor.GaussianNoise
      ++defense.defense_params.scale: range(0.1, 1, 0.1)
defense_alias: gaussian-noise
