# @package _global_
hydra:
  sweeper:
    params:
      ++defense.defense_name: art.defences.postprocessor.HighConfidence
      ++defense.defense_params.cutoff: range(0.1, .9, 0.1)
defense_alias: high-confidence