defaults:
- _self_
- data: torch_mnist
- sampler@data.sampler: split
- model: default
- trainer@model.trainer: pretrained
- defense: class_labels
- attack: fgm
- files: default

experiment_name: pytorch_pretrained_default

hydra:
  run:
    dir: output/logs/${experiment_name}
