[project]
name = "deckard"
version = "0.95.0"
description = "A tool for declarative AI experimentation, evaluation, and verification."
authors = [
    { name = "simplymathematics" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
dependencies = [
    "pandas",
    "scikit-learn",
    "hydra-core",
    "numpy",
    "adversarial-robustness-toolbox",
    "matplotlib",
    "dvc",
    "ipykernel",
    "kagglehub",
    "cma",
    "optuna-dashboard",
    "hydra-joblib-launcher",
    "hydra-optuna-sweeper @ git+https://github.com/simplymathematics/hydra-optuna-sweeper.git",
    "optuna>=3",
    "paretoset",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["deckard"]

[project.optional-dependencies]
lifelines = [
    "lifelines",
]

fairlearn = [
    "fairlearn",
]

anjana = [
    "anjana @ git+https://github.com/IFCA-Advanced-Computing/anjana.git",
]

yellowbrick = [
    "yellowbrick",
]

seaborn = [
    "seaborn",
]

docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "myst-parser",
    "nbsphinx"
]

test = [
    "pytest",
    "pytest-cov",
    "flake8",
    "black",
    "isort",
    "mypy",
    "pre-commit",
    "pandas",
    "numpy"
]

torch = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "torchaudio>=2.0.0",
    "cma",
]

# Linting
lint = [
    "flake8",
    "black",
    "isort",
    "mypy",
    "pre-commit",
    "flake8-pyproject",
]


# All extras
all  = [
    "pandas",
    "scikit-learn",
    "hydra-core",
    "numpy",
    "adversarial-robustness-toolbox",
    "seaborn",
    "yellowbrick",
    "fairlearn",
    "anjana @ git+https://github.com/IFCA-Advanced-Computing/anjana.git",
    "lifelines",
    "matplotlib",
    "dvc",
    "optuna",
    "paretoset",
    "ipykernel",
    "kagglehub",
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "myst-parser",
    "nbsphinx",
    "pytest",
    "pytest-cov",
    "flake8",
    "black",
    "isort",
    "mypy",
    "pre-commit",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "torchaudio>=2.0.0",
    "cma",
    "lifelines",

]

[tool.black]
line-length = 87
target-version = ['py310']
include = 'deckard/.*\.py'

[project.scripts]
deckard = "deckard.__main__:main"

[tool.flake8]
max-line-length = 87
exclude = [
  "__pycache__",
  "*.egg-info",
  ".git",
  ".venv",
  "build",
  "docs"
]

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::UserWarning",
        "ignore::RuntimeWarning",
        "ignore::sklearn.exceptions.ConvergenceWarning",
        "ignore::DeprecationWarning",
        "ignore::FutureWarning",
        "ignore::matplotlib.MatplotlibDeprecationWarning"
]
