# @package _global_
hydra:
  sweeper:
    params:
      ++model.model_params.C: choice(0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)
      ++model.model_params.coef0: choice(0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)
model_alias: rbf
