name: art.attacks.evasion.ProjectedGradientDescent
attack_params:
  eps: 0.1
  eps_step: 0.01
  norm: 2
  max_iter: 10
  batch_size: 100
  targeted: false
attack_size: 100
_target_: deckard.attack.AttackConfig
alias: pgd
