stages:
  generate_data:
    cmd: python -m deckard.layers.runner generate_data
    params:
      - data
      - files
    outs:
      - ${files.data_file}
    metrics:
      - ${files.reports}/generate_data/${files.path}
    deps:
      - params.yaml
  train:
    cmd: python -m deckard.layers.runner train
    params:
      - data
      - model.init
      - files
      - scorers
    deps:
      - ${files.data_file}
    # outs:
      # - ${files.data_file}
      # - train/${files.model_file}
    metrics:
      - ${files.reports}/train/${files.path}/
  attack : 
    cmd : python -m deckard.layers.runner attack 
    metrics:
      - ${files.reports}/attack/${files.path}/
    params:
      - data
      - model.init
      - attack
      - files
      - scorers
    deps:
      - ${files.reports}/train/${files.path}/
  # retrain:
  #   cmd : python retrain.py
  #   params: 
  #     - data
  #     - model.init
  #     - model.art_pipeline
  #     - attack
  #     - files
  #     - scorers
  #   deps:
  #     - attack/
  #   outs:
  #     - retrain/
  # model_queue:
  #   cmd: bash experiments.sh 
  #   outs:
  #     - model_queue/
  #   deps:
  #     - attack/
  # compile_results:
  #   cmd : python -m deckard.layers.compile
  #   outs: 
  #     - best
  #   metrics:
  #     - newest_results.csv
  #   deps:
  #     - model_queue/
  