stages:
  generate_data:
    cmd: python -m deckard.layers.runner generate_data
    params:
      - data
      - files
    outs:
      - generate_data/${files.data_file}
    metrics:
      - ${files.reports}/generate_data/${files.path}
    deps:
      - params.yaml
  train:
    cmd: python -m deckard.layers.runner train
    params:
      - data
      - model
      - files
      - scorers
    deps:
      - generate_data/${files.data_file}
    outs:
      - train/${files.data_file}
      - train/${files.model_file}
    metrics:
      - ${files.reports}/train/${files.path}/
  attack : 
    cmd : python -m deckard.layers.runner attack 
    outs:
      - attack/
    params:
      - data
      - model
      - attack
      - files
      - scorers
    deps:
      - train/
  # generate_queue:
  #   cmd: bash experiments.sh 
  #   outs:
  #     - queue/
  #   deps:
  #     - train/${files.data_file}
  #     - train/${files.model_file}
  # compile_results:
  #   cmd : python -m deckard.layers.compile
  #   outs: 
  #     - best
  #   metrics:
  #     - newest_results.csv
  #   deps:
  #     - queue/
  