stages:
  generate_data:
    cmd: python -m deckard.layers.runner generate_data --layer data
    params:
      - data
      - files
    outs:
      - ${data.files.data_path}/generate_data/
  train:
    cmd: python -m deckard.layers.runner train
    params:
      - data
      - model.files
      - model.init
      - files
      - plots
      - scorers
    deps:
      - ${data.files.data_path}/generate_data/
    outs:
      - ${data.files.data_path}/train/
      - ${model.files.model_path}/train/
      - ${files.path}/train
  pipeline:
    cmd: python -m deckard.layers.runner pipeline
    params:
      - data
      - model.files
      - model.init
      - files
      - plots
      - scorers
    deps:
      - ${model.files.model_path}/train/
      - ${data.files.data_path}/train/
    outs:
      - ${files.path}/pipeline
      - ${model.files.model_path}/pipeline/
      - ${data.files.data_path}/pipeline/
  defend:
    cmd: python -m deckard.layers.runner defend
    params:
      - data
      - model.files
      - model.init
      - model.art_pipeline
      - files
      - plots
      - scorers
    deps:
      - ${model.files.model_path}/pipeline/
      - ${data.files.data_path}/pipeline/
    outs:
      - ${files.path}/defend
      - ${model.files.model_path}/defend/
      - ${data.files.data_path}/defend/
  attack:
    cmd: python -m deckard.layers.runner attack
    params:
      - data
      - model
      - attack
      - files
      - plots
      - scorers
    deps:
      - ${model.files.model_path}/defend/
      - ${data.files.data_path}/defend/
    outs:
      - ${files.path}/attack