stages:
  attack:
    cmd: python -m deckard.layers.runner attack
    deps:
    - ${files.data_file}
    - ${files.reports}/train/${files.path}/${files.params_file}
    metrics:
    - ${files.reports}/attack/${files.path}/${files.score_dict_file}
    - ${files.reports}/attack/${files.path}/${files.time_dict_file}
    - ${files.reports}/attack/${files.path}/${files.predictions_file}
    - ${files.reports}/attack/${files.path}/${files.probabilities_file}
    - ${files.reports}/attack/${files.path}/${files.attack_score_dict_file}
    - ${files.reports}/attack/${files.path}/${files.attack_time_dict_file}
    - ${files.reports}/attack/${files.path}/${files.attack_predictions_file}
    - ${files.reports}/attack/${files.path}/${files.attack_probabilities_file}
    outs:
    - ${files.reports}/attack/${files.path}/${files.params_file}
    - ${files.reports}/attack/${files.path}/${files.attack_samples_file}
    params:
    - data
    - model.init
    - files
    - scorers
    - attack
  generate_data:
    cmd: python -m deckard.layers.runner generate_data
    deps:
    - params.yaml
    metrics:
    - ${files.reports}/generate_data/${files.path}/${files.ground_truth_file}
    outs:
    - ${files.data_file}
    params:
    - data
    - files
  train:
    cmd: python -m deckard.layers.runner train
    deps:
    - ${files.data_file}
    metrics:
    - ${files.reports}/train/${files.path}/${files.score_dict_file}
    - ${files.reports}/train/${files.path}/${files.time_dict_file}
    - ${files.reports}/train/${files.path}/${files.predictions_file}
    - ${files.reports}/train/${files.path}/${files.probabilities_file}
    outs:
    - ${files.reports}/train/${files.path}/${files.params_file}
    params:
    - data
    - model.init
    - files
    - scorers
retrain:
    cmd : python retrain.py
    params: 
      - data
      - model.init
      - model.art_pipeline
      - attack
      - files
      - scorers
    deps:
      - attack/
    outs:
      - retrain/
  model_queue:
    cmd: bash experiments.sh 
    outs:
      - model_queue/
    deps:
      - attack/
  compile_results:
    cmd : python -m deckard.layers.compile
    outs: 
      - best
    metrics:
      - newest_results.csv
    deps:
      - model_queue/
  attack_queue:
    cmd: bash attacks.sh 
    outs:
      - attack_queue/
    deps:
      - best/
