data:  ${data}
init:
    _target_: deckard.base.model.ModelInitializer
    name : tfv2_example.TFNet
    optimizer :
        class_name : SGD
        config:
            learning_rate : 0.001
    loss_object:
        class_name: CategoricalCrossentropy
        config:
            from_logits: true

_target_: deckard.base.model.Model
trainer:
    nb_epoch: 1
    batch_size: 64
library : tensorflow
art:
    _target_ : deckard.base.model.art_pipeline.ArtPipeline
    library : ${model.library}
    initialize:
