vars:
  - conf/knn.yaml:hydra
  - conf/plots.yaml:line_plot
  - conf/plots.yaml:cat_plot
  # - conf/condensed_plots.yaml:line_plot
  # - conf/clean.yaml:params
  - conf/clean.yaml:fillna
  - conf/clean.yaml:replace
stages:
  ##############################################################################
  # These stages use the dvc API to run a single experiment at a time using a
  # deckard.Experiment object. This parses this file, saves the default hydra configuration
  # to params.yaml, and then runs the experiment with the given parameters.
  # This can be used to define a stage that runs a single experiment, or a stage for the
  # optimisation using the optimise.py script and the hydrasweeper API. This API is primarily used for
  # development and testing, as it is easier to run a single experiment at a time and debug it using
  # DVC's git-like features to track changes and minimise run time. 

  # This stage will parse the conf/knn.yaml file and save it to params.yaml
  # In addition, it will define a schema stage that will will 
  # 1. Determine the file paths for the data and model files (if specified)
  # 2. Run the experiment with the given parameters
  # 3. Save the results to the configured file paths (score and params files)
  # 4. Save a 'params.yaml' file with the scores (Always)
  # 5. Save the predictions to the given file paths (if specified)
  # 6. Save the probabilities to the given file paths (if specified)
  # 7. Save the (final) losses to the given file paths (if specified)
  # 8. Save the train/test labels to the given file paths (if specified)

  # You can arbitrarily define parameters in the 'conf' folder.
  # To parse the parameters, you can use the 'hydra' API to define a schema for the parameters
  # Or run `deckard.layers.parse` to parse the parameters and save them to a file.  
  ##############################################################################

  
  ##############################################################################
  install dependencies:
    cmd: >-
      pip install imbalanced-learn brotli zstd Levenshtein &&
      python -c "import imblearn, brotli, Levenshtein, importlib.metadata as md; open('requirements.txt', 'w', encoding='utf-8').write(f'imbalanced-learn=={imblearn.__version__}\\nbrotli=={brotli.__version__}\\nzstd=={md.version(\"zstd\")}\\nLevenshtein=={Levenshtein.__version__}\\n')"
    outs:
      - requirements.txt:
          cache: false
          persist: true

  ##############################################################################
  data:
    cmd: python data_prep.py
    deps:
      - data_prep.py
      - requirements.txt
    outs:
      - raw_data/:
          cache: true
          persist: true
          push: true

  ##############################################################################
  grid_search_precompute:
    matrix: 
      train_size: [1000] 
      dataset: [ddos, kdd_nsl, sms_spam, truthseeker]
      metric : [gzip, bz2, brotli, levenshtein, ratio, hamming]
      algorithm : # zero-hack, sort-hack, average-hack, alias
        - [False, False, False, "Vanilla"]
        - [False, True, False, "Assumed"]
        - [True, True, False, "Enforced"]
        - [True, False, True, "Average"]
    cmd: >-
      deckard optimize
      algorithm="${item.algorithm[3]}"
      data=${item.dataset}
      ++data.sampler.train_size=${item.train_size}
      ++data.random_state=42
      ++data.split=0
      ++data.pre_sample_transform=true
      optimization=precompute
      metric_name=${item.metric}
      fold_name=full
      ++data.pipeline.distance.metric=${item.metric}
      ++data.pipeline.distance.zero_hack=${item.algorithm[0]}
      ++data.pipeline.distance.sort_hack=${item.algorithm[1]}
      ++data.pipeline.distance.average_hack=${item.algorithm[2]}
      ++data.pipeline.distance.distance_matrix_full=output/${item.dataset}/distance_matrix/${item.metric}/${item.algorithm[3]}/full.npz
      files=precompute
      hydra.sweeper.n_trials=1
      --config-dir config
      --config-name default
    deps:
      - config/default.yaml
      - config/data/default.yaml
      - config/data/precompute.yaml
      - config/model/ncd_knn.yaml
      - raw_data/
    outs:
      - output/${item.dataset}/distance_matrix/${item.metric}/${item.algorithm[3]}/full.npz:
            cache: false
            persist: true
            push: true
      - output/logs/precompute_${item.dataset}_knn_${item.algorithm[3]}_${item.metric}_${item.train_size}_full/:
            cache: false
            persist: false
    params:
      - config/default.yaml:
          - hydra
  ##############################################################################
  grid_search:
    matrix: 
      train_size: [1000] # 10, 20, 35, 60, 100, 200, 500  200, 500
      dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
      metric : [gzip, bz2, brotli, levenshtein, ratio, hamming]
      model_name : [knn,logistic, svc] # knn, svc, logistic
      algorithm : # zero-hack, sort-hack, average-hack, alias
        - [False, False, False, "Vanilla"]
        - [False, True, False, "Assumed"] 
        - [True, True, False, "Enforced"]
        - [True, False, True, "Average"]
    cmd: >-
      deckard optimize
      algorithm="${item.algorithm[3]}"
      data=${item.dataset}
      model=ncd_${item.model_name}
      data.sample.name=deckard.data.sample.KFoldSampler
      ++data.sampler.train_size=${item.train_size}
      ++data.random_state=42
      optimization=search
      metric_name=${item.metric}
      ++data.pipeline.distance.metric=${item.metric}
      ++data.pipeline.distance.zero_hack=${item.algorithm[0]}
      ++data.pipeline.distance.sort_hack=${item.algorithm[1]}
      ++data.pipeline.distance.average_hack=${item.algorithm[2]}
      ++data.pipeline.distance.distance_matrix_full=output/${item.dataset}/distance_matrix/${item.metric}/${item.algorithm[3]}/full.npz
      hydra.sweeper.n_jobs=1
      hydra.sweeper.n_trials=1
      hydra.sweeper.params.data.split=int(range(0,5))
      hydra.launcher.n_jobs=1
      ++data.pipeline=${item.model_name}
      --config-dir config
      --config-name default
      --multirun
    deps:
      - config/default.yaml
      - config/data/default.yaml
      - config/data/${item.model_name}.yaml
      - config/model/ncd_${item.model_name}.yaml
      - config/search/models/${item.model_name}.yaml
      - raw_data/
      - output/${item.dataset}/distance_matrix/${item.metric}/${item.algorithm[3]}/full.npz
    outs:
      - output/logs/search_${item.dataset}_${item.model_name}_${item.algorithm[3]}_${item.metric}_${item.train_size}_all/:
            cache: false
            persist: false
      - output/${item.dataset}/reports/search/${item.model_name}/${item.algorithm[3]}/${item.train_size}/${item.metric}/:
            cache: false
            persist: true
    params:
      - config/default.yaml:
          - hydra
  # #############################################################################
  # find_best:
  #   matrix:
  #     dataset : [ddos, kdd_nsl, sms_spam, truthseeker]
  #     algorithm : [Vanilla, Assumed, Enforced, Average]
  #     model : [knn, svc, logistic]
  #     metric : [gzip, bz2, brotli, levenshtein, ratio, hamming]
  #   deps:
  #     - output/${item.dataset}/reports/search/${item.model}/${item.algorithm}/
  #     - conf/model/ncd_${item.model}.yaml
  #     - conf/${item.model}.yaml
  #     - find_best.py
  #   cmd: >-
  #     find_best
  #     -n ${item.dataset}_${item.model}_${item.algorithm}
  #     -p sqlite:///output/optuna.db
  #     -d conf/model/ncd_${item.model}.yaml
  #     -c conf/${item.model}.yaml
  #     -s model.init.metric=${item.metric}
  #     -o best/${item.dataset}_${item.model}_${item.algorithm}_${item.metric}.yaml
  #     -x model.init.distance_matrix_train model.init.distance_matrix_test files.directory data.sample.fold
  #   outs:
  #   - best/${item.dataset}_${item.model}_${item.algorithm}_${item.metric}.yaml
  # # ##############################################################################
  # refit_best:
  #   matrix:
  #     train_size: [10, 20, 35, 60, 100, 200, 500, 1000] 
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker]
  #     algorithm : [Vanilla, Assumed, Enforced, Average]
  #     model : [knn, svc, logistic]
  #     metric : [gzip, bz2, brotli, levenshtein, ratio, hamming]
  #   deps:
  #     - output/${item.dataset}/reports/search/${item.model}/${item.algorithm}/
  #     - best/${item.dataset}_${item.model}_${item.algorithm}_${item.metric}.yaml
  #   cmd: >-
  #     deckard.layers.optimise
  #     algorithm="${item.algorithm}"
  #     data.sample.train_size=${item.train_size}
  #     dataset=${item.dataset}
  #     data.sample.fold=-1
  #     model_name=${item.model}
  #     files.directory=output/${item.dataset}
  #     hydra.run.dir=output/${item.dataset}/logs/refit/${item.model}/${item.algorithm}/${item.metric}/${item.train_size}/
  #     --config-name ${item.dataset}_${item.model}_${item.algorithm}_${item.metric}
  #     --config-dir best
  #   outs:
  #   - output/${item.dataset}/reports/refit/${item.model}/${item.algorithm}/${item.metric}/${item.train_size}/
  #   - output/${item.dataset}/logs/refit/${item.model}/${item.algorithm}/${item.metric}/${item.train_size}/
  # ##############################################################################
  # compile:
  #   matrix:
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
  #     model : [knn, svc, logistic, ] #condense/knn, condense/svc, condense/logistic
  #     stage : [search, refit]
  #   deps:
  #     - output/${item.dataset}/reports/${item.stage}/${item.model}/
  #   outs:
  #   - output/${item.dataset}/${item.stage}/${item.model}.csv
  #   cmd: >-
  #     deckard.layers.compile 
  #     --report_folder output/${item.dataset}/reports/${item.stage}/${item.model}/
  #     --results_file output/${item.dataset}/${item.stage}/${item.model}.csv
  # ##############################################################################
  # compile_precomputed:
  #   matrix:
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
  #     model : [knn] # Only one model is needed because the distance matrix is the same for all models
  #     stage : [precomputed]
  #   deps:
  #     - output/${item.dataset}/reports/${item.stage}/${item.model}/
  #   outs:
  #   - output/${item.dataset}/${item.stage}/${item.model}.csv
  #   cmd: >-
  #     deckard.layers.compile 
  #     --report_folder output/${item.dataset}/reports/${item.stage}/${item.model}/
  #     --results_file output/${item.dataset}/${item.stage}/${item.model}.csv
  # ##############################################################################  
  # clean:
  #   matrix:
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
  #     model : [knn, svc, logistic,] 
  #     stage : [search, refit]
  #   deps: 
  #     - output/${item.dataset}/${item.stage}/${item.model}.csv
  #   cmd: >-
  #     deckard.layers.clean_data 
  #     -i output/${item.dataset}/${item.stage}/${item.model}.csv
  #     -o output/${item.dataset}/plots/${item.stage}/${item.model}.csv
  #     -c conf/clean.yaml
  #   outs:
  #     - output/${item.dataset}/plots/${item.stage}/${item.model}.csv
  #   params:
  #     - conf/clean.yaml:
  #       - replace
  #       - drop_values
  #       - replace_cols
  #       - fillna
  # ##############################################################################
  # clean_precomputed:
  #   matrix: 
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
  #     model : [knn] # Only one model is needed because the distance matrix is the same for all models
  #     stage : [precomputed]
  #   deps:
  #     - output/${item.dataset}/${item.stage}/${item.model}.csv
  #   cmd: >-
  #     deckard.layers.clean_data 
  #     -i output/${item.dataset}/${item.stage}/${item.model}.csv
  #     -o output/${item.dataset}/plots/${item.stage}/${item.model}.csv
  #     -c conf/clean.yaml
  #   outs:
  #     - output/${item.dataset}/plots/${item.stage}/${item.model}.csv
  #   params:
  #     - conf/clean.yaml:
  #       - replace
  #       - drop_values
  #       - replace_cols
  #       - fillna
  # ##############################################################################
  # merge_search:
  #   matrix:
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
  #     stage : [search, refit]
  #   deps:
  #     - output/${item.dataset}/plots/${item.stage}/knn.csv
  #     - output/${item.dataset}/plots/${item.stage}/logistic.csv
  #     - output/${item.dataset}/plots/${item.stage}/svc.csv
  #   cmd: >-
  #     python merge.py
  #     --big_dir output/${item.dataset}/plots/
  #     --data_file ${item.stage}/knn.csv
  #     --little_dir_data_file ${item.stage}/logistic.csv ${item.stage}/svc.csv
  #     --output_folder output/${item.dataset}/plots
  #     --output_file ${item.stage}_merged.csv
  #   outs:
  #     - output/${item.dataset}/plots/${item.stage}_merged.csv
  # ##############################################################################
  # merge_search_datasets:
  #   cmd: >-
  #     python merge.py
  #     --big_dir output/
  #     --little_dir output/
  #     --data_file ddos/plots/search_merged.csv
  #     --little_dir_data_file  kdd_nsl/plots/search_merged.csv sms_spam/plots/search_merged.csv truthseeker/plots/search_merged.csv 
  #     --output_file search_merged.csv
  #     --output_folder output/combined/plots/
  #   deps:
  #     - output/sms_spam/plots/search_merged.csv
  #     - output/kdd_nsl/plots/search_merged.csv
  #     - output/ddos/plots/search_merged.csv
  #     - output/truthseeker/plots/search_merged.csv
  #   outs:
  #     - output/combined/plots/search_merged.csv
  # ##############################################################################
  # merge_refit_datasets:
  #   cmd: >-
  #     python merge.py
  #     --big_dir output/
  #     --little_dir output/
  #     --data_file ddos/plots/refit_merged.csv
  #     --little_dir_data_file  kdd_nsl/plots/refit_merged.csv sms_spam/plots/refit_merged.csv truthseeker/plots/refit_merged.csv 
  #     --output_file refit_merged.csv
  #     --output_folder output/combined/plots/
  #   deps:
  #     - output/sms_spam/plots/refit_merged.csv
  #     - output/kdd_nsl/plots/refit_merged.csv
  #     - output/ddos/plots/refit_merged.csv
  #     - output/truthseeker/plots/refit_merged.csv
  #   outs:
  #     - output/combined/plots/refit_merged.csv
  # ##############################################################################
  # merge_precomputed:
  #   matrix:
  #     dataset: [ddos, kdd_nsl, sms_spam, truthseeker] 
  #     stage : [precomputed]
  #   deps:
  #     - output/${item.dataset}/plots/${item.stage}/knn.csv
  #   cmd: >-
  #     python merge.py
  #     --big_dir output/${item.dataset}/plots/
  #     --data_file ${item.stage}/knn.csv
  #     --output_folder output/${item.dataset}/plots
  #     --output_file ${item.stage}_merged.csv
  #   outs:
  #     - output/${item.dataset}/plots/${item.stage}_merged.csv
  # ##############################################################################
  # merge_precomputed_datasets:
  #   cmd: >-
  #     python merge.py
  #     --big_dir output/
  #     --little_dir output/
  #     --data_file ddos/plots/precomputed_merged.csv
  #     --little_dir_data_file  kdd_nsl/plots/precomputed_merged.csv sms_spam/plots/precomputed_merged.csv truthseeker/plots/precomputed_merged.csv 
  #     --output_file precomputed_merged.csv
  #     --output_folder output/combined/plots/
  #   deps:
  #     - output/sms_spam/plots/precomputed_merged.csv
  #     - output/kdd_nsl/plots/precomputed_merged.csv
  #     - output/ddos/plots/precomputed_merged.csv
  #     - output/truthseeker/plots/precomputed_merged.csv
  #   outs:
  #     - output/combined/plots/precomputed_merged.csv
  # ##############################################################################
  # plot_merged:
  #   cmd: >-
  #     python plots.py
  #   deps:
  #     - output/combined/plots/search_merged.csv
  #     - output/combined/plots/precomputed_merged.csv
  #     - output/combined/plots/refit_merged.csv
  #     - plots.py
  #   plots:
  #     - output/combined/plots/pred_time_vs_algorithm.pdf
  #     - output/combined/plots/train_time_vs_algorithm.pdf
  #     - output/combined/plots/accuracy_vs_kernel.pdf
  #     - output/combined/plots/accuracy_vs_algorithm.pdf
  #     - output/combined/plots/distance_matrix_time_vs_algorithm.pdf
  #     - output/combined/plots/accuracy_vs_train_size.pdf
  #   outs:
  #     - output/combined/plots/search_averaged.csv:
  #         cache: false
  #         persist: true
  #         push: true
  # copy:
  #   cmd: >-
  #     rm -rf ~/Gzip-KNN/images/combined/ &&
  #     mkdir -p ~/Gzip-KNN/images/combined/ &&
  #     cp -r output/combined/plots/*.pdf ~/Gzip-KNN/images/ && 
  #     cp -r output/combined/plots/*.csv ~/Gzip-KNN/data/
  #   deps:
  #     - output/combined/
  # ##############################################################################
  # metric_space_check:
  #   deps:
  #     - metric_space_check.py
  #   cmd: >-
  #     python metric_space_check.py
  #     --max_alphabet_size 52
  #     --max_string_size 144
  #     --sig_figs 10
  #     --data random
  #     --samples 1000
  #     --folder metric_space_check/
  #     --log_file metric_space_check.log
  #     --results_file results.csv
  #     --plot_file synthetic_check.pdf
  #   outs:
  #     - metric_space_check/results.csv
  #     - metric_space_check/metric_space_check.log
  #     - metric_space_check/synthetic_check.pdf
  # copy_metric_space_check:
  #   cmd: >-
  #     cp -r metric_space_check/*pdf ~/Gzip-KNN/images/ &&
  #     cp -r metric_space_check/*csv ~/Gzip-KNN/data/
  #   deps:
  #     - metric_space_check/
  # ##############################################################################
  # check_matrices:
  #   deps:
  #     - output/ddos/distance_matrix/
  #     - output/kdd_nsl/distance_matrix/
  #     - output/sms_spam/distance_matrix/
  #     - output/truthseeker/distance_matrix/
  #     - check_matrices.py
  #   cmd: >-
  #     python check_matrices.py
  #     --working_dir output
  #     --file_regex */distance_matrix/**/train-*.npz
  #     --results_plot read_world_check.pdf
  #     --results_file real_world_failures.csv
  #   outs:
  #     - check_matrices/real_world_failures.csv
  #     - check_matrices/check_matrices.log
  #     - check_matrices/melted.csv
  #     - check_matrices/read_world_check.pdf
  # copy_check_matrices:
  #   cmd: >-
  #     cp -r check_matrices/*pdf ~/Gzip-KNN/images/ &&
  #     cp -r check_matrices/*csv ~/Gzip-KNN/data/
  #   deps:
  #     - check_matrices/
