stages:
  prepare:
    cmd: python -m deckard.layers.prepare
    params:
      - prepare
    outs: 
      - data.pkl
  train:
    cmd:  python -m deckard.layers.sklearn_model --layer_name train
    deps:
    - data.pkl
    params:
    - train
    outs:
    - train/:
        cache: true
  preprocess:
    cmd: python -m deckard.layers.preprocess  --layer_name preprocess --position 0
    deps:
    - train/
    params:
      - preprocess
    outs:
    - preprocess/:
        cache: true
  featurize:
    cmd: python -m deckard.layers.preprocess --layer_name featurize --position 1
    deps:
    - preprocess/
    params:
      - featurize
    outs:
    - featurize/:
        cache: true
  visualise:
    cmd: python -m deckard.layers.visualise --layer_name visualise
    deps: 
      - train/
    params:
      - visualise
    outs:
      - plots/:
          cache: true
  control:
    cmd:  python -m deckard.layers.art_model --layer_name control
    deps:
    - data.pkl
    params:
    - control
    outs:
    - control/:
        cache: true
  defend:
    cmd:  python -m deckard.layers.defend --layer_name defend
    deps:
    - data.pkl
    - control/
    params:
    - defend
    outs:
    - defences/:
        cache: true
  attack:
    cmd:  python -m deckard.layers.attack --layer_name attack
    deps:
    - data.pkl
    - defences/
    params:
    - attack
    outs:
    - attacks/:
        cache: true
  evaluate:
    cmd: python -m deckard.layers.evaluate --layer_name evaluate
    deps: 
      - featurize/
      - control/
      - preprocess/
      - train/
      - attacks/
      - defences/
    params:
      - evaluate
    outs:
      - scores/


