vars:
  data_file  : "data.pickle"
  model_file : "model.pickle"
  predictions_file : "predictions.json"
  ground_truth_file : "ground_truth.json"
  scores_file : "scores.json"
  params_file : "params.json"
  plot_file : "plot.pdf"
  

prepare:
  inputs:
    folder : 
    file : 
  config:
    name: 'iris'
    params:
      shuffle : True
      stratify : True
      random_state : 0
      test_size : 
      train_size : .8
  outputs:
    folder : "."
    file : ${data_file}
    predictions : 
    ground_truth : 
  scores:
    file: 
    folder:
    time_dict:
  plots:
    file:
    folder:
train:
  inputs:
    folder :
    data : 
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.linear_model.LogisticRegression
    params: 
      'penalty' : 'l2'
  outputs:
    folder : "."
    model : "train_model.pickle"
    params : "train_params.json"
    ground_truth : "train_ground_truth.json"
    predictions : "train_predictions.json"
  metrics:
    scores : "train_scores.json"
preprocess:
  inputs:
    folder : train.outputs.folder
    data : train.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    position : 0
    model: train.outputs.model
  config : 
    name: sklearn.preprocessing.StandardScaler
    params: 
      'with_mean' : True
      'with_std' : True
  outputs:
    folder : "."
    model : "preprocess_model.pickle"
    params : "preprocess_params.json"
    ground_truth : "preprocess_ground_truth.json"
    predictions : "preprocess_predictions.json"
  metrics:
    scores : "preprocess_scores.json"
featurize:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    position : 1
    model: preprocess.outputs.model
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "featurize_model.pickle"
    params : "featurize_params.json"
    ground_truth : "featurize_ground_truth.json"
    predictions : "featurize_predictions.json"
  metrics:
    scores : "featurize_scores.json"
art:
  inputs:
    folder : featurize.outputs.folder
    data : featurize.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : False
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "art_model.pickle"
    params : "art_params.json"
  metrics:
    scores : "art_scores.json"
defend:
  inputs:
    folder : art.outputs.folder
    data : art.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : False
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "defend_model.pickle"
    params : "defend_params.json"
  metrics:
    scores : "defend_scores.json"
attack:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "attackd_model.pickle"
    params : "attack_params.json"
  metrics:
    scores : "attack_scores.json"
evaluate:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "evaluate_model.pickle"
    params : "evaluate_params.json"
  metrics:
    scores : "evaluate_scores.json"
visualise:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "visualise_model.pickle"
    params : "visualise_params.json"
  metrics:
    scores : "visualise_scores.json"