vars:
  data_file  : "data.pickle"
  model_file : "model.pickle"
  predictions_file : "predictions.json"
  ground_truth_file : "ground_truth.json"
  scores_file : "scores.json"
  params_file : "params.json"
  plot_file : "plot.pdf"
  

prepare:
  inputs:
    folder : 
    file : 
  config:
    name: 'iris'
    params:
      shuffle : True
      stratify : True
      random_state : 0
      test_size : 
      train_size : .8
  outputs:
    folder : prepare
    file : data.pickle
    predictions : 
    ground_truth : 
  scores:
    file: 
    folder: 
    time_dict: 
  plots:
    file:
    folder:
train:
  inputs:
    folder : prepare
    data : data.pickle
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.linear_model.LogisticRegression
    params: 
      'penalty' : 'l2'
  outputs:
    folder : train
    model : "model.pickle"
    ground_truth : "ground_truth.json"
    predictions : "predictions.json"
  metrics:
    scores : params.scores_file
preprocess:
  inputs:
    folder : "."
    data : train.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    position : 0
    model: train.outputs.model
  config : 
    name: sklearn.preprocessing.StandardScaler
    params: 
      'with_mean' : True
      'with_std' : True
  outputs:
    folder : "preprocess"
    model : "model.pickle"
    params : "params.json"
    ground_truth : "ground_truth.json"
    predictions : "predictions.json"
  metrics:
    scores : "scores.json"
featurize:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    position : 1
    model: preprocess.outputs.model
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : featurize
    model : "model.pickle"
    params : "params.json"
    ground_truth : "ground_truth.json"
    predictions : "predictions.json"
  metrics:
    scores : "scores.json"
art:
  inputs:
    folder : featurize.outputs.folder
    data : featurize.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : False
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "art_model.pickle"
    params : "art_params.json"
  metrics:
    scores : "art_scores.json"
defend:
  inputs:
    folder : art.outputs.folder
    data : art.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : False
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "defend_model.pickle"
    params : "defend_params.json"
  metrics:
    scores : "defend_scores.json"
attack:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "attack_model.pickle"
    params : "attack_params.json"
  metrics:
    scores : "attack_scores.json"
evaluate:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "model.pickle"
    params : "params.json"
  metrics:
    scores : "scores.json"
visualise:
  inputs:
    folder : preprocess.outputs.folder
    data : preprocess.outputs.file
    type : 'sklearn'
    classifier : True
    is_fitted : True
    model: 
  config : 
    name: sklearn.impute.SimpleImputer
    params: 
      'strategy' : 'mean'
  outputs:
    folder : "."
    model : "model.pickle"
    params : "params.json"
  metrics:
    scores : "scores.json"
