defaults:
    - _self_
    - data: ???
    - model: gzip_knn
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : tpe
    - override hydra/launcher : joblib
dataset : ???
model_name : gzip_knn
stage : train
direction : 
  - maximize
optimizers: 
   - accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${dataset}/logs/${stage}/
  sweep:
    dir: ???
    subdir : ${hydra.job.num}
  callbacks:
    study_dump:
      _target_ : database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : ${direction}
      metric_names : ${optimizers}
      output_file : ${dataset}/logs/${model_name}/${data.sample.train_size}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: true
      n_startup_trials: 32
      n_ei_candidates: 32
      multivariate: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: ${direction}
    storage: sqlite:///optuna.db
    study_name: ???
    n_trials: ${oc.env:DECKARD_TRIALS, 128}
    n_jobs: ${oc.env:DECKARD_JOBS, 8}
    max_failure_rate: 1.0
    params:
      model.init.k : 3
      +model.init.weights : uniform,distance
      +model.init.algorithm : brute
      model.init.symmetric : True,False
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: ${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
