defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: ???
    - model: gzip_svc
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : tpe
    - override hydra/launcher : joblib
dataset : ???
model_name : gzip_svc
stage : train
direction : 
  - maximize
optimizers: 
   - accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${dataset}/logs/${stage}/
  sweep:
    dir: ???
    subdir : ${hydra.job.id}
  callbacks:
    study_dump:
      _target_ : optuna_database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : ${direction}
      metric_names : ${optimizers}
      output_file : ${dataset}/logs/${model_name}/${data.sample.train_size}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 256
      multivariate: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${dataset}_${model_name}_condense
    storage: sqlite:///optuna.db
    n_jobs: ${oc.env:DECKARD_JOBS, 8}
    n_trials : ${oc.env:DECKARD_TRIALS, 128}
    params:
      +model.init.kernel : rbf,precomputed
      +model.init.C : tag(log, interval(1e-3, 1e3))
      +model.init.gamma : scale,auto
      +model.init.class_weight : balanced,null
      ++model.init.max_iter : 1000
    direction: ${direction}
    max_failure_rate: 1.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 8
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: ${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
