defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: kdd_nsl
    - model: default
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : grid
    - override hydra/launcher : joblib
dataset : kdd_nsl
model_name : gzip_knn
stage : train
direction : 
  - maximize
optimizers: 
   - accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${files.directory}/logs/${stage}/
  sweep:
    dir: ${files.directory}/logs/
    subdir : ${hydra.sweeper.study_name}/${hydra.job.id}
  callbacks:
      study_dump:
        _target_ : database.OptunaStudyDumpCallback
        storage : ${hydra.sweeper.storage}
        study_name : ${hydra.sweeper.study_name}
        directions : ${direction}
        metric_names : ${optimizers}
        output_file : ${files.directory}/${hydra.sweep.dir}/${hydra.sweeper.study_name}.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${model_name}_${dataset}
    storage: sqlite:///optuna.db
    n_jobs: 1
    n_trials : 1
    params:
    direction: ${direction}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: n_jobs*2
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
