defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: ???
    - model: gzip_svc
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : tpe
    - override hydra/launcher : joblib
dataset : ???
model_name : gzip_svc
stage : train
direction : 
  - maximize
optimizers: 
   - accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${dataset}/logs/${stage}/
  sweep:
    dir: ???
    subdir : ${hydra.job.id}
  callbacks:
    study_dump:
      _target_ : database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : 
        - maximize
      metric_names : 
        - accuracy
      output_file : ${dataset}/logs/${model_name}/${data.sample.train_size}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${dataset}_${model_name}_${stage}
    storage: sqlite:///optuna.db
    n_jobs: 2
    n_trials : 2
    params:
      +model.init.kernel : rbf,precomputed
      +model.init.C : 1e-2,1e-1,1e0,1e1,1e2
      +model.init.gamma : scale,auto
      +model.init.class_weight : balanced,null
      model.init.symmetric : True,False
      ++model.init.precompute : True
      model.init.metric : gzip,lzma,bz2,pkl,zstd,levenshtein,ratio,hamming,jaro,jaro_winkler,seqratio
      model_name : ${model_name}
      data.sample.random_state: int(interval(1, 10000))
    direction: ${direction}
    max_failure_rate: 1.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 8
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: ${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
