defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: kdd_nsl
    - model: ncd_knn
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : grid
    - override hydra/launcher : joblib
dataset : ${data.alias}
model_name : knn
algorithm : Vanilla
stage : train
direction : maximize
optimizers: accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: output/${dataset}/logs/precomputed/${model_name}/${algorithm}/${data.sample.train_size}/${data.sample.fold}/${model.init.metric}/
  sweep:
    dir: output/${dataset}/logs/search/${model_name}/${algorithm}/${data.sample.train_size}/${data.sample.fold}/${model.init.metric}/
    subdir : ${hydra.job.num}
  callbacks:
    study_dump:
      _target_ : optuna_database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : maximize
      metric_names : accuracy
      output_file :  ${hydra.sweep.dir}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: ${direction}
    storage: sqlite:///output/optuna.db
    study_name: ${dataset}_${model_name}_${algorithm}
    n_trials: 4096
    n_jobs: 1
    max_failure_rate: 1.0
    params:
      model.init.k : 1,3,5
      +model.init.weights : uniform,distance
      +model.init.algorithm : brute
      model_name : ${model_name}
      model.init.metric: gzip,bz2,brotli,levenshtein,ratio,hamming
      model.init.symmetric: True,False
      model.init.modified: True,False
      model.init.transform: None,abs,square
      data.sample.fold: 0,1,2,3,4
      files.reports: reports/search/${model_name}/${algorithm}/${data.sample.train_size}/${data.sample.fold}/${data.sample.test_size}/${data.sample.random_state}/
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 1
    prefer : processes
    verbose: 1
    timeout: ${oc.env:DECKARD_TIMEOUT, 1800}
    pre_dispatch: 2*${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
