defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: ???
    - model: ncd_logistic
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : tpe
    - override hydra/launcher : joblib
dataset : ???
model_name : logistic
stage : train
direction : maximize
optimizers: accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${dataset}/logs/${stage}/
  sweep:
    dir: ???
    subdir : ${hydra.job.id}
  callbacks:
    study_dump:
      _target_ : owptuna_database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : ${direction}
      metric_names : ${optimizers}
      output_file :  ${hydra.sweep.dir}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      consider_prior: true
      seed: 123
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: true
      n_startup_trials: 128
      n_ei_candidates: 8
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${dataset}_${model_name}_${stage}
    storage: sqlite:///output/optuna.db
    n_trials: 256
    n_jobs: 16
    params:
      +model.init.solver: saga
      +model.init.penalty : l2,l1
      +model.init.tol: tag(log, interval(1e-5, 1e-1))
      +model.init.C : tag(log, interval(1e-3, 1e3))
      +model.init.fit_intercept : True,False
      +model.init.class_weight : balanced,None
      ++model.init.modified: True,False
      ++model.init.condensing_method: medoid,sum,svc,random,hardness,nearmiss,knn,None
      ++model.init.transform: None,abs,square,exp_neg,exp_neg_gamma_001,exp_neg_gamma_01,exp_neg_gamma_1,exp_neg_gamma10,exp_neg_gamma100,exp_neg_gamma1000
      model.init.max_iter: 1000
      ++model.init.symmetric: True,False
      model_name : ${model_name}
    direction: ${direction}
    max_failure_rate: 1.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 8
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: ${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
