defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: ???
    - model: default
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : tpe
    - override hydra/launcher : joblib
dataset : ???
model_name : ???
stage : train
direction : 
  - maximize
optimizers: 
   - accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${dataset}/logs/${stage}/
  sweep:
    dir: ${dataset}/logs/${hydra.sweeper.study_name}/
    subdir : ${hydra.job.id}
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${model_name}_${data.sample.train_size}_${data.sample.random_state}
    storage: sqlite:///optuna.db
    n_jobs: 1
    n_trials : 1
    params:
      model.init.k : 1,3,5,7,11
      model.init.m : 10,20,50,100,200,500
      model.init.symmetric : True,False
      model.init.metric : levenshtein,ratio,hamming,jaro,jaro_winkler
      model.init.method : random,svc,medoid,sum,knn
      model_name : ${model_name}
    direction: ${direction}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 16
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: n_jobs
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
