defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: default
    - model: ncd_svc
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : grid
    - override hydra/launcher : joblib
dataset : ${data.alias}
algorithm : Vanilla
model_name : svc
stage : train
direction: maximize
optimizers: accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: output/${dataset}/logs/precomputed/${model_name}/${algorithm}/${model.init.metric}/${data.sample.train_size}/${data.sample.fold}/
  sweep:
    dir: output/${dataset}/logs/search/${model_name}/${algorithm}/${model.init.metric}/${data.sample.train_size}/${data.sample.fold}/
    subdir : ${hydra.job.num}
  callbacks:
    study_dump:
      _target_ : optuna_database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : maximize
      metric_names : accuracy
      output_file :  ${hydra.sweep.dir}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${dataset}_${model_name}_${algorithm}_${model.init.metric}
    storage: sqlite:///output/optuna.db
    n_trials: 1
    n_jobs: ${oc.env:DECKARD_N_JOBS, 1}
    direction: ${direction}
    params:
      +model.init.C : .0001,.001,.01,.1,1,10,100,1000
      model_name : ${model_name}
      model.init.symmetric: True,False
      model.init.modified: True,False
      model.init.metric: gzip,bz2,brotli,levenshtein,ratio,hamming
      data.sample.fold: 0,1,2,3,4
      model.init.transform: exp_neg,rbf_gamma_001,rbf_gamma_01,rbf_gamma_1,rbf_gamma10,rbf_gamma100,rbf_gamma1000
    max_failure_rate: 1.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: ${oc.env:DECKARD_N_JOBS, 1}
    prefer : processes
    verbose: 1
    timeout: ${oc.env:DECKARD_TIMEOUT, 1800}
    pre_dispatch: ${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
