defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: ???
    - model: ncd_svc
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : tpe
    - override hydra/launcher : joblib
dataset : ???
model_name : svc
stage : train
direction : 
  - maximize
optimizers: 
   - accuracy
device_id : ${oc.env:DECKARD_DEVICE_ID, "cpu"}
hydra:
  run:
    dir: ${dataset}/logs/${stage}/
  sweep:
    dir: ???
    subdir : ${hydra.job.id}
  callbacks:
    study_dump:
      _target_ : database.OptunaStudyDumpCallback
      storage : ${hydra.sweeper.storage}
      study_name : ${hydra.sweeper.study_name}
      directions : 
        - maximize
      metric_names : 
        - accuracy
      output_file : ${dataset}/logs/${model_name}/${data.sample.train_size}/study.csv
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      consider_prior: true
      seed: 123
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: true
      n_startup_trials: 128
      n_ei_candidates: 8
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${dataset}_${model_name}_${stage}
    storage: sqlite:///output/optuna.db
    n_trials: 128
    n_jobs: 8
    params:
      +model.init.kernel : rbf,precomputed
      +model.init.C : tag(log, interval(1e-3, 1e3))
      +model.init.gamma : scale,auto
      +model.init.class_weight : balanced,null
      model_name : ${model_name}
      model.init.symmetric: true,false
      ++model.init.modified: True,False
      ++model.init.condensing_method: medoid,sum,svc,random,hardness,nearmiss,knn,None
      ++data.sample.random_state: int(range(0, 1000))
    direction: ${direction}
    max_failure_rate: 1.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 8
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: ${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
