stages:
  prepare:
    cmd:
      - python -m deckard.layers.runner prepare
    deps:
      - original.csv
    outs:
      - prepare/${files.data_file}
    params:
      - data
      - files
      - plots
  train:
    cmd: python -m deckard.layers.runner train
    deps:
    - prepare/${files.data_file}
    params:
    - data
    - files
    - model
    - plots
    - scorers
    outs:
    - train/${files.model_file}
    metrics:
    - ${files.reports}/train/${files.path}/${files.score_dict_file}
