defaults:
    - _self_
    - data: adult
    - model: rf
    - attack: membership
    - files: null
    - override hydra/sweeper : optuna
experiment_name: ???
directions:
- maximize
- maximize
optimizers:
- accuracy
- evasion_accuracy
hydra:
  run:
    dir: outputs/logs/${experiment_name}
  sweep:
    dir: outputs/logs/
    subdir: ${hydra.sweeper.study_name}/${hydra.job.num}
  sweeper:
    study_name: evasion_attack
    storage: sqlite:///optuna.db
    direction: ${directions}
    sampler:
      _target_: optuna.samplers.TPESampler
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: true
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    n_trials: 100
    n_jobs: 1
    params:
        ++model.model_params.n_estimators: int(range(0,1000))
        ++model.model_params.max_depth: int(range(1,101))
        ++model.model_params.max_leaf_nodes: int(range(1,1000))

