
defaults:
    - art : default
data:  ${data}
init:
    _target_: deckard.base.model.ModelInitializer
    num_channels : 1
    name : torch_example.ResNet18
_target_: deckard.base.model.Model
trainer:
    nb_epoch: 20
    batch_size: 1024
library : pytorch
