stages:
  data:
    cmd: python make_data.py
    outs:
    - ${files.data_file}
    plots:
    - ${files.path}/balance.png
    - ${files.path}/radviz.png
    - ${files.path}/correlation.png
    params:
    - data
    deps:
    - params.yaml
  model:
    cmd: python experiment.py
    outs:
    - ${files.model_file}
    - ${files.path}/${files.predictions_file}
    - ${files.path}/${files.ground_truth_file}
    - ${files.path}/report.html
    deps:
    - ${files.data_file}
    - params.yaml
    metrics:
    - ${files.path}/scores.json
    plots:
    - ${files.path}/classification.png
    - ${files.path}/confusion.png
    params:
    - model
  cache:
    cmd: python cache.py
    deps:
    - ${files.data_file}
    - ${files.model_file}
    - ${files.path}/${files.ground_truth_file}
    - ${files.path}/${files.predictions_file}
