stages:
  data:
    cmd: python make_data.py
    outs:
    - ${files.data_file}
    plots:
    - ${files.path}/balance.png
    - ${files.path}/radviz.png
    - ${files.path}/correlation.png
    params:
    - data
  model:
    cmd: python experiment.py
    outs:
    - ${files.model_file}
    - ${files.path}/${files.predictions_file}
    - ${files.path}/${files.ground_truth_file}
    - ${files.path}/report.html
    deps:
    - ${files.data_file}
    metrics:
    - ${files.path}/scores.json
    plots:
    - ${files.path}/classification.png
    - ${files.path}/confusion.png
    params:
    - model
  # cache:
  #   cmd: python hash.py
  #   deps:
  #   - ${files.data_file}
  #   - ${files.model_file}
  #   - ${files.path}/${files.ground_truth_file}
  #   - ${files.path}/${files.predictions_file}
  #   outs:
  #   - experiments/:
  #       cache: true
  #       persist: true
  #       desc: Final report folder for website.
