stages:
  data:
    cmd: python make_data.py
    outs:
    - data/data.npz
    - data/ground_truth.csv
    plots:
    - report/balance.png
    - report/radviz.png
    - report/correlation.png
    params:
    - data
  model:
    cmd: python tikhonov.py
    outs:
    - model/model.pickle
    - model/predictions.csv
    deps:
    - data/data.npz
    metrics:
    - model/scores.csv
    plots:
    - report/classification.png
    - report/confusion.png
    params:
    - model
  cache:
    cmd: python hash.py
    deps:
    - report/
    - data/data.npz
    - model/model.pickle
    - data/ground_truth.csv
    - model/predictions.csv
    outs:
    - experiments/:
        cache: true
        persist : true
        desc : Final report folder for website.


  
      
