stages:
  print_params:
    cmd: cat params.yaml
  # data:
  #   cmd: python make_data.py
  #   outs:
  #   - data/data.npz
  #   - data/ground_truth.csv
  #   plots:
  #   - reports/balance.png
  #   - reports/radviz.png
  #   - reports/correlation.png
  #   params:
  #   - data
  # model:
  #   cmd: python tikhonov.py
  #   outs:
  #   - model/model.pickle
  #   - predictions.csv
  #   deps:
  #   - data/data.npz
  #   metrics:
  #   - scores.csv
  #   plots:
  #   - reports/classification.png
  #   - reports/confusion.png
  #   params:
  #   - model