stages:
    data:
      cmd: python make_data.py
      outs:
      - data/data.npz
      - data/ground_truth.csv
      plots:
      - reports/balance.png
      - reports/radviz.png
      - reports/correlation.png
      params:
      - data.add_noise
      - data.classification
      - data.plots
      - data.files
    model:
      cmd: python tikhonov.py
      outs:
      - model/model.pickle
      - model/predictions.csv
      deps:
      - data/data.npz
      metrics:
      - model/scores.csv
      plots:
      - reports/classification.png
      - reports/confusion.png
      params:
      - model.files
      - model.metrics
      - model.params
      - model.plots
    build_queue :
      cmd:
      - dvc exp run --set-param data.add_noise.X_train=.001,.01,.1,1,10,100 --queue
      - dvc exp run --set-param model.params.scale=.001,.01,.1,1,10,100 --queue
      - dvc exp run --set-param model.params.scale=.001,.01,.1,1,10,100 --queue
      - dvc exp run --set-param model.params.scale=.001,.01,.1,10,100 --set-param
        data.add_noise.X_test=.001,.01,.1,1,10,100 --queue
      - dvc exp run --set-param model.params.learning_rate=1e-11,1e-10,1e-9 model.params.scale=.001,.01,.1,10,100
      - dvc
      deps:
      - data/data.npz
      - model/model.pickle
      outs:
      - queue.csv
    training_with_tikho:
      cmd: dvc exp run --set-param model.params.scale=.001,.01,.1,1,10,100 --queue
      deps:
      - data/data.npz
      - model/model.pickle
    testing_tikho_with_noise:
      cmd: dvc exp run --set-param model.params.scale=.001,.01,.1,10,100 --set-param
        data.add_noise.X_test=.001,.01,.1,1,10,100 --queue
      deps:
      - data/data.npz
      - model/model.pickle
