stages:
  set_config_paths:
    cmd: >
      echo "export DECKARD_CONFIG_DIR=./config" > .deckard_rc &&
      echo "export DECKARD_DEFAULT_CONFIG_FILE=torch_mnist.yaml" >> .deckard_rc &&
      echo "export DECKARD_NJOBS=1" >> .deckard_rc
    outs:
      - .deckard_rc
    deps:
      - ./config/torch_mnist.yaml

  power_search:
    cmd: >
      deckard optimize
      stage=attack
      experiment_name=power_torch_mnist
      hydra.sweeper.study_name=power_torch_mnist
      ++hydra.sweeper.storage=sqlite:///output/optuna.db
      --multirun
      ++attack.attack_size=100
      ++attack.init.eps=interval(0.01,1.0)
      --config-name torch_mnist.yaml
      &&
      deckard optimize
      stage=attack
      experiment_name=power_torch_cifar10
      hydra.sweeper.study_name=power_torch_cifar10
      ++hydra.sweeper.storage=sqlite:///output/optuna.db
      --multirun
      ++attack.attack_size=100
      ++attack.init.eps=interval(0.01,1.0)
      --config-name torch_cifar10.yaml
      &&
      deckard optimize
      stage=attack
      experiment_name=power_torch_cifar100
      hydra.sweeper.study_name=power_torch_cifar100
      ++hydra.sweeper.storage=sqlite:///output/optuna.db
      --multirun
      ++attack.attack_size=100
      ++attack.init.eps=interval(0.01,1.0)
      --config-name torch_cifar100.yaml
    deps:
      - .deckard_rc
      - ./config/torch_mnist.yaml
      - ./config/torch_cifar10.yaml
      - ./config/torch_cifar100.yaml
      - ../../deckard
    outs:
      - output/logs/
      - output/optuna.db

  compile_results:
    cmd: >
      python -m deckard.layers.compile_results
      --output_file output/combined/power_results.csv
      --optuna_db sqlite:///output/optuna.db
    deps:
      - output/optuna.db
      - ./config/torch_mnist.yaml
      - ./config/torch_cifar10.yaml
      - ./config/torch_cifar100.yaml
      - ../../deckard
    outs:
      - output/combined/power_results.csv
