stages:
  train:
    cmd: python -m deckard.layers.experiment train
    params:
      - data
      - model
      - scorers
      - files
    outs:
      - ${files.directory}/${files.data_dir}/${files.data_file}${files.data_type}
      - ${files.directory}/${files.model_dir}/${files.model_file}${files.model_type}
      - ${files.directory}/${files.reports}/train/${files.train_labels_file}
      - ${files.directory}/${files.reports}/train/${files.test_labels_file}
      - ${files.directory}/${files.reports}/train/${files.predictions_file}
      - ${files.directory}/${files.reports}/train/${files.probabilities_file}
    metrics:
      - ${files.directory}/${files.reports}/train/${files.score_dict_file}
  attack:
    cmd: python -m deckard.layers.experiment attack
    params:
      - data.generate
      - model
      - attack
      - scorers
      - files
    outs:
      - ${files.directory}/${files.attack_dir}/${files.attack_file}${files.attack_type}
      - ${files.directory}/${files.reports}/attack/${files.adv_predictions_file}
      - ${files.directory}/${files.reports}/attack/${files.adv_probabilities_file}
    deps:
      - ${files.directory}/${files.data_dir}/${files.data_file}${files.data_type}
      - ${files.directory}/${files.model_dir}/${files.model_file}${files.model_type}
    metrics:
      - ${files.directory}/${files.reports}/attack/${files.score_dict_file}
