defaults:
    - _self_
    - data: default
    - model: default
    - attack: hsj
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/launcher : joblib
hydra:
  run:
    dir : "./${files.directory}"
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      # seed: 123
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    study_name: model
    storage: sqlite:///model.db
    n_trials: 100
    n_jobs: 1
  launcher:
    _target_: hydra_plugins.hydra_rq_launcher.rq_launcher.RQLauncher
    enqueue:
      job_timeout: null
      ttl: null
      result_ttl: null
      failure_ttl: null
      at_front: false
      job_id: null
      description: null
    queue: default 
    redis:
      host: ${oc.env:REDIS_HOST,localhost}
      port: ${oc.env:REDIS_PORT,6379}
      db: ${oc.env:REDIS_DB,0}
      password: ${oc.env:REDIS_PASSWORD,null}
      ssl: ${oc.env:REDIS_SSL,False}
      ssl_ca_certs: ${oc.env:REDIS_SSL_CA_CERTS,null
      mock: ${oc.env:REDIS_MOCK,False}
    stop_after_enqueue: false
    wait_polling: 1.0
