defaults:
  - _self_
  - data : default.yaml
  - model : default.yaml
  - scorers/accuracy : default.yaml
  - scorers/f1 : default.yaml
  - scorers/precision : default.yaml
  - scorers/recall : default.yaml
  - files : default.yaml
  - attack : default.yaml
  # - plots : default.yaml
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid
  - override hydra/launcher: joblib
#@package hydra.launcher
hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction:
    - maximize
    storage: sqlite:///db.sqlite3
    study_name: models
    n_trials : 1000
    n_jobs : 32
    # params:
    # data.generate.n_features : choice(10, 100, 1000, 10000)
    # data.sample.train_size : choice(10, 100, 10000, 10000, 100000, 1000000)
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 32
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: n_jobs
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r


    