defaults:
  - _self_
  - data : default.yaml
  - model : default.yaml
  - scorers/accuracy : default.yaml
  - scorers/f1 : default.yaml
  - scorers/precision : default.yaml
  - scorers/recall : default.yaml
  - files : default.yaml
  - attack : default.yaml
  # - plots : default.yaml
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid
  - override hydra/launcher: joblib
#@package hydra.launcher
hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction:
    - maximize
    storage: sqlite:///db.sqlite3
    study_name: models
    n_trials : 1000
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 32
    backend: multiprocessing
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 4*n_jobs
    batch_size: 32
    temp_folder: /tmp/deckard
    max_nbytes: null
    mmap_mode: r


    