defaults:
  - _self_
  - data/files : default.yaml
  - data/generate : default.yaml
  - data/sample : default.yaml
  - data/name : default.yaml
  - model/files : default.yaml
  - model/init : svc.yaml
  # - model/art_pipeline/postprocessor: default.yaml
  # - model/art_pipeline/preprocessor: default.yaml
  # - plots: default.yaml
  - scorers/accuracy : default.yaml
  - scorers/f1 : default.yaml
  - scorers/precision : default.yaml
  - scorers/recall : default.yaml
  - files : default.yaml
  - attack/init : default.yaml
  - attack/generate : default.yaml
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid
hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction:
    - maximize
    storage: null
    study_name: pareto
    n_jobs: 32
    