data:  ${data}
library : keras
init:
    name : keras_example.MNISTNet
    loss: categorical_crossentropy
    optimizer: SGD
    metrics: accuracy
_target_: deckard.base.model.Model
trainer:
    nb_epoch: 1
    batch_size: 1024
art:
    library : ${model.library}
    initialize:
