defaults:
- _self_
- data: imdb_sentiment
- model: hf_bert_imdb_tuned
- trainer@model.trainer: pytorch
- attack: hsj
- files: default

experiment_name: transformers_hsj_imdb_tuned

hydra:
  run:
    dir: output/logs/${experiment_name}
