defaults:
- _self_
- data: mathqa_arithmetic
- model: hf_distilbert_arithmetic
- trainer@model.trainer: pytorch
- attack: hsj
- files: default

experiment_name: transformers_hsj_arithmetic

hydra:
  run:
    dir: output/logs/${experiment_name}
