defaults:
- _self_
- data: ag_news_topic
- model: hf_bert_agnews_tuned
- trainer@model.trainer: pytorch
- attack: hsj
- files: default

experiment_name: transformers_hsj_agnews_tuned

hydra:
  run:
    dir: output/logs/${experiment_name}
