defaults:
- _self_
- data: sst2_sentiment
- model: hf_distilbert_sst2_tuned
- trainer@model.trainer: pytorch
- attack: hsj
- files: default

experiment_name: transformers_hsj_sst2_tuned


hydra:
  run:
    dir: output/logs/${experiment_name}
