_target_: deckard.base.scorer.ScorerDict
accuracy:
    _target_: deckard.base.scorer.ScorerConfig
    name: sklearn.metrics.accuracy_score
    direction: maximize
log_loss:
    _target_: deckard.base.scorer.ScorerConfig
    name: sklearn.metrics.log_loss
    direction: minimize
