defense_name: art.defences.preprocessor.FeatureSqueezing
init_params:
    library: art
    type: preprocessor
    class: FeatureSqueezing
defense_params:
    apply_fit : False
    apply_predict : True
    bit_depth: 8
    clip_values: [0, 255]
_target_ : deckard.DefenseConfig
alias: feature-squeezing
