_target_: deckard.attack.AttackConfig
attack_size: 10
name: art.attacks.evasion.FastGradientMethod
attack_params:
  eps: 0.99
  batch_size: ${model.fit_params.batch_size}
  targeted: false
  minimal: true
