# @package _global_
hydra:
  sweeper:
    params:
      ++attack.attack_params.scale_max: choice(0.1, 0.2, 0.3, 0.5, 0.8, 0.9, 0.99)
      ++attack.attack_params.batch_size: choice(100)
attack_alias: adversarial-patch
