stages:
  set_config_paths:
      cmd: >
        echo "export DECKARD_CONFIG_DIR=./config" > .deckard_rc &&
        echo "export DECKARD_DEFAULT_CONFIG_FILE=default.yaml" >> .deckard_rc &&
        source .deckard_rc
      outs: 
        - .deckard_rc
      deps:
        - ./config/default.yaml
      params:
        - ./config/default.yaml:
  simple_example:
      cmd: deckard optimize experiment_name=default
      deps:
        - .deckard_rc # Here to ensure config paths are set before running deckard
        - ../../deckard
        - ./config/default.yaml

  defend_evasion:
    matrix:
      data: 
        - adult
        # - classification
        # - digits
      model:
        - rf
        # - svc
        - logistic
      defense:
        # Postprocessing defenses
        # - class-labels
        - gaussian-noise
        - high-confidence
        # - reverse-sigmoid
        # - rounded
        # # Preprocessing defenses
        # - cut-mix
        # - cutout
        # - feature-squeezing
        - gaussian-augmentation
        # - jpeg-compression
        - label-smoothing
        # - mixup
        # - resample
        # - spatial-smoothing
      attack:
        # - hsj
        - boundary
    cmd: >
      deckard optimize
      data=${item.data} 
      +files.data_file=outputs/data/${item.data}.pkl
      model=${item.model}
      attack=${item.attack}
      defense=${item.defense}
      experiment_name=*
      hydra.sweeper.study_name=defended_${item.data}_${item.model}_${item.defense}_${item.attack}_evasion
      --multirun
    deps:
      - ./config/default.yaml
    outs:
      - outputs/logs/defended_${item.data}_${item.model}_${item.defense}_${item.attack}_evasion/
    params:
      - ./config/default.yaml:
        - defaults
        - hydra
  defend_attribute-inference:
    matrix:
      data: 
        - adult
      model:
        - rf
        - logistic
      defense:
        - gaussian-noise
        - high-confidence
    cmd: >
      deckard optimize
      data=${item.data} 
      +files.data_file=outputs/data/${item.data}.pkl
      model=${item.model}
      attack=attribute-bb
      defense=${item.defense}
      experiment_name=defended_${item.data}_${item.model}_${item.defense}/*
      hydra.sweeper.study_name=defended_${item.data}_${item.model}_${item.defense}_attribute-inference
      --config-name attribute-inference-default
      --multirun
    deps:
      - outputs/data/${item.data}.pkl
      - ./config/inference-default.yaml
    outs:
      - outputs/logs/defended_${item.data}_${item.model}_${item.defense}_attribute-inference
    params:
      - ./config/inference-default.yaml:
        - defaults
        - hydra
  defend_membership_inference:
    matrix:
      data: 
        - adult
      model:
        - rf
        - logistic
      defense:
        - gaussian-noise
        - high-confidence
    cmd: >
      deckard optimize
      data=${item.data} 
      +files.data_file=outputs/data/${item.data}.pkl
      model=${item.model}
      attack=membership
      defense=${item.defense}
      experiment_name=defended_${item.data}_${item.model}_${item.defense}/*
      hydra.sweeper.study_name=defended_${item.data}_${item.model}_${item.defense}_membership-inference
      --config-name inference-default
      --multirun
    deps:
      - outputs/data/${item.data}.pkl
      - ./config/inference-default.yaml
    outs:
      - outputs/logs/defended_${item.data}_${item.model}_${item.defense}_membership-inference
    params:
      - ./config/inference-default.yaml:
        - defaults
        - hydra
        