stages:
  set_config_paths:
      cmd: >
        echo "export DECKARD_CONFIG_DIR=./config" > .deckard_rc &&
        echo "export DECKARD_DEFAULT_CONFIG_FILE=default.yaml" >> .deckard_rc &&
        source .deckard_rc
      outs: 
        - .deckard_rc
      deps:
        - ./config/default.yaml
      params:
        - ./config/default.yaml:
  simple_example:
      cmd: deckard experiment_name=default && echo "Deckard ran successfully!" > deckard.log
      outs:
        - deckard.log
      deps:
        - .deckard_rc # Here to ensure config paths are set before running deckard
        - ../../deckard
        - ./config/default.yaml
  generate_data:
      foreach:
        - adult
        # - classification
        # - diabetes
        # - digits
        # - regression
        # - kdd_nsl
        # - ddos
        # - sms_spam
        # - truthseeker
      do:
        cmd: >
          deckard 
          data=${item} 
          +files.data_file=outputs/data/${item}.pkl 
          +files.score_file=outputs/scores/data/${item}.json
          experiment_name=${item}
          ~model 
          ~attack
          ~directions
          ~optimizers
        outs:
          - outputs/data/${item}.pkl
        metrics:
          - outputs/scores/data/${item}.json
        deps:
          - .deckard_rc
          - ../../deckard/data/
        params:
          - ./config/data/${item}.yaml:
          ################################################
          #            Command Explanation:             #
          ################################################
          # deckard  <-- Calls the deckard CLI tool
          # data=${item}  <-- Specifies the dataset to be used in this iteration. See ./config/data/ for available datasets.
          # +files.data_file=data/${item}.pkl <-- Specifies the output path for the generated data file.
          # +files.score_file=scores/${item}.json <-- Specifies the output path for the score file.
          # ~model <-- Drops default model configuration.
          # ~attack <-- Drops default attack configuration.
          ################################################
  train:
      matrix:
        data: 
          - adult
          # - classification
          # - digits
        model:
          - rf
          # - svc
          # - logistic
      cmd: >
        deckard 
        data=${item.data} 
        +files.data_file=outputs/data/${item.data}.pkl 
        +files.model_file=outputs/models/${item.data}/${item.model}.pkl
        +files.score_file=outputs/scores/models/${item.data}/${item.model}.json
        experiment_name=${item.data}_${item.model}
        model=${item.model}.yaml 
        ~attack
        ~directions
        ~optimizers
      outs:
        - outputs/models/${item.data}/${item.model}.pkl
      metrics:
        - outputs/scores/models/${item.data}/${item.model}.json
      deps:
        - outputs/data/${item.data}.pkl
        - ../../deckard/model
      params:
        - ./config/model/${item.model}.yaml:
        - ./config/data/${item.data}.yaml:
        ################################################
        #            Command Explanation:             #
        ################################################
        # deckard  <-- Calls the deckard CLI tool
        # model=${item}  <-- Specifies the model to be trained for this iteration. See ./config/model/ for available models.
        # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
        # +files.model_file=models/${item}/model.pkl <-- Specifies the output path for the trained model file.
        # +files.score_file=scores/models/${item}/model.json <-- Specifies the output path for the model score file.
        # model=rf.yaml  <-- Specifies the model configuration to be used.
        # ~attack <-- Drops default attack configuration.
  attack_rf:
    matrix:
      data: 
        - adult
        # - classification
        # - digits
      model:
        - rf
        # - svc
        # - logistic
      attack:
        # Evasion attacks
        - hsj
        - boundary
        # TODO: Poisoning attacks
        # Membership inference attacks
        - membership
        # Attribute inference attacks
        # - attribute-bb
    cmd: >
      deckard 
      data=${item.data} 
      +files.data_file=outputs/data/${item.data}.pkl 
      +files.model_file=outputs/models/${item.data}/${item.model}.pkl
      +files.score_file=outputs/scores/attacks/${item.data}/${item.model}/${item.attack}.json
      model=${item.model}.yaml 
      attack=${item.attack}.yaml
      experiment_name=${item.data}_${item.model}_${item.attack}
      ~directions
      ~optimizers
    metrics:
      - outputs/scores/attacks/${item.data}/${item.model}/${item.attack}.json
    deps:
      - outputs/data/${item.data}.pkl
      - outputs/models/${item.data}/${item.model}.pkl
  defend_rf:
    matrix:
      data: 
        - adult
        # - classification
        # - digits
      model:
        - rf
        # - svc
        # - logistic
      defense:
          # Postprocessing defenses
          - class_labels
          - gaussian_noise
          - high_confidence
          - reverse_sigmoid
          - rounded
          # Preprocessing defenses
          - cut_mix
          - cutout
          - feature_squeezing
          - gaussian_augmentation
          - label_smoothing
          - mixup
    cmd:
      deckard 
      data=${item.data} 
      +files.data_file=outputs/data/${item.data}.pkl 
      +files.model_file=outputs/models/${item.data}/${item.model}_defended_${item.defense}.pkl
      +files.score_file=outputs/scores/defenses/${item.data}/${item.model}_${item.defense}.json
      model=${item.model}.yaml 
      model.alias=${item.model}_${item.defense}
      defense=${item.defense}.yaml
      experiment_name=${item.data}_${item.model}_defended_${item.defense}
      ~attack
      ~directions
      ~optimizers
    outs:
      - outputs/models/${item.data}/${item.model}_defended_${item.defense}.pkl
    metrics:
      - outputs/scores/defenses/${item.data}/${item.model}_${item.defense}.json
    deps:
      - outputs/data/${item.data}.pkl
      - ../../deckard/model
    params:
      - ./config/model/rf.yaml:
      - ./config/defense/${item.defense}.yaml:
      - ./config/data/${item.data}.yaml:
      ################################################
      #            Command Explanation:             #
      ################################################
      # deckard  <-- Calls the deckard CLI tool
      # data=${item}  <-- Specifies the dataset to be used in this iteration. See ./config/data/ for available datasets.
      # +files.data_file=data/${item}.pkl
      # +files.model_file=models/${item}/model_defended_${item.defense}.pkl <-- Specifies the output path for the defended model file.
      # +files.score_file=scores/defenses/${item}_${item.defense}.json
      # model=rf.yaml  <-- Specifies the model configuration to be used.
      # +defense=${item.defense}.yaml  <-- Specifies the defense configuration to be
      # used.
  defend:
    matrix:
      data: 
        - adult
        # - classification
        # - digits
      model:
        - rf
        # - svc
        # - logistic
      defense:
        # Postprocessing defenses
        # - class_labels
        - gaussian_noise
        - high_confidence
        # - reverse_sigmoid
        # - rounded
        # # Preprocessing defenses
        # - cut_mix
        # - cutout
        # - feature_squeezing
        - gaussian_augmentation
        # - jpeg_compression
        - label_smoothing
        # - mixup
        # - resample
        # - spatial_smoothing
      attack:
        # - hsj
        - boundary
    cmd: >
      deckard 
      data=${item.data} 
      data_alias=${item.data}
      +files.data_file=outputs/data/${item.data}.pkl
      model=${item.model}
      model_alias=${item.model}
      attack_alias=${item.attack}
      attack=${item.attack}
      defense=${item.defense}
      defense_alias=${item.defense}
      experiment_name=*
      hydra.sweeper.study_name=defended_${item.data}_${item.model}_${item.defense}_${item.attack}
      --multirun
    deps:
      - outputs/data/${item.data}.pkl
      - ./config/default.yaml
    outs:
      - outputs/logs/defended_${item.data}_${item.model}_${item.defense}_${item.attack}/
    params:
      - ./config/default.yaml:
        - defaults
        - hydra
  evade:
    matrix:
      data: 
        - adult
        # - classification
        # - digits
      model:
        - rf
        # - svc
        # - logistic
      attack:
        # Evasion attacks
        # - hsj
        - boundary
      defense:
      # Postprocessing defenses
        # - class_labels
        - gaussian_noise
        # - high_confidence
      #   - reverse_sigmoid
      #   - rounded
      # # Preprocessing defenses
      #   - cut_mix
      #   - cutout
        # - feature_squeezing
        - gaussian_augmentation
        # - jpeg_compression
      #   - label_smoothing
      #   - mixup
      #   - resample
      #   - spatial_smoothing
    cmd: >
      deckard 
      data=${item.data} 
      data_alias=${item.data}
      +files.data_file=outputs/data/${item.data}.pkl
      +files.score_file=outputs/scores/attacks/${item.data}_${item.model}_${item.defense}_${item.attack}/*.json
      experiment_name=evaded_${item.data}_${item.model}_${item.defense}_${item.attack}/*
      defense=${item.defense}
      defense_alias=${item.defense}
      model=${item.model}
      model_alias=${item.model}
      attack=${item.attack}
      attack_alias=${item.attack}
      hydra.sweeper.study_name=evaded_${item.data}_${item.model}_${item.defense}_${item.attack}
      --config-name attack_default
      --multirun
    deps:
      - outputs/data/${item.data}.pkl
      - ./config/attack_default.yaml
    outs:
      - outputs/logs/evaded_${item.data}_${item.model}_${item.defense}_${item.attack}
    params:
      - ./config/attack_default.yaml:
        - defaults
        - hydra
    ################################################
    #            Command Explanation:             #
    ################################################
    # deckard  <-- Calls the deckard CLI tool
    # data=${item}  <-- Specifies the dataset to be used in this iteration. See ./config/data/ for available datasets.
    # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
    # +files.score_file=scores/${item}/${item.model}/${item.defense}/${item
    # model=${item.model}  <-- Specifies the model to be used. See ./config/model/ for available models.
    # attack=${item.attack}  <-- Specifies the attack to be used. See ./config/attack/ for available attacks.
    # defense=${item.defense}  <-- Specifies the defense to be used. See ./config/defense/ for available defenses.
    # multiple runs to be logged under the same experiment name.
    # hydra.sweeper.study_name=...  <-- Sets a unique study name for each combination of data,
    # model, defense, and attack.
    # --config-name attack_default  <-- Uses the attack_default configuration for this run.
    # --multirun  <-- Enables multiple runs for hyperparameter optimization.
  infer_membership:
    matrix:
      data: 
        - adult
        # - classification
        # - digits
      model:
        - rf
        - svc
        - logistic
      defense:
      # Postprocessing defenses
        # - class_labels
        - gaussian_noise
        - high_confidence
      #   - reverse_sigmoid
      #   - rounded
      # # Preprocessing defenses
      #   - cut_mix
      #   - cutout
      #   - feature_squeezing
        - gaussian_augmentation
      #   - jpeg_compression
        - label_smoothing
      #   - mixup
      #   - resample
      #   - spatial_smoothing
    cmd: >
      deckard 
      data=${item.data}
      data_alias=${item.data}
      +files.data_file=outputs/data/${item.data}.pkl
      experiment_name=membership_${item.data}_${item.model}_${item.defense}/*
      model=${item.model}
      model_alias=${item.model}
      attack=membership
      attack_alias=membership
      defense=${item.defense}
      defense_alias=${item.defense}
      hydra.sweeper.study_name=membership_${item.data}_${item.model}_${item.defense}
      --config-name inference_default
      --multirun
    deps:
      - outputs/data/${item.data}.pkl
      - ./config/attack_default.yaml
    outs:
      - outputs/logs/membership_${item.data}_${item.model}_${item.defense}
    params:
      - ./config/attack_default.yaml:
        - defaults
        - hydra
    ################################################
    #            Command Explanation:             #
    ################################################
    # deckard  <-- Calls the deckard CLI tool
    # data=${item}  <-- Specifies the dataset to be used in this iteration. See ./config/data/ for available datasets.
    # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
    # +files.score_file=scores/${item}/${item.model}/${item.defense}/${item
    # model=${item.model}  <-- Specifies the model to be used. See ./config/model/ for available models.
    # attack=membership <-- Specifies the attack to be used. See ./config/attack/ for available attacks.
    # defense=${item.defense}  <-- Specifies the defense to be used. See ./config/defense/ for available defenses.
