defaults:
    - art : default
data:  ${data}
init:
    _target_: deckard.base.model.ModelInitializer
    name : torch_example.ResNet18
    num_channels: 3
    num_classes: 100
_target_: deckard.base.model.Model
trainer:
    nb_epoch: 1
    batch_size: 128
    verbose: True
library : pytorch
art:
    initialize:
        criterion:
        name : torch.nn.CrossEntropyLoss
    optimizer:
        name : torch.optim.SGD
        lr : 0.01
        momentum : 0.9
    clip_values : [0, 255]