
defaults:
    - art : default
data:  ${data}
init:
    _target_: deckard.base.model.ModelInitializer
    name : torch_example.ResNet18
    # name : torch_example.ResNet50
    # name : torch_example.ResNet101
    # name : torch_example.ResNet152
_target_: deckard.base.model.Model
trainer:
    nb_epoch: 20
    batch_size: 1024
library : pytorch
