defaults:
    - art : default
data:  ${data}
init:
    _target_: deckard.base.model.ModelInitializer
    name : torch_example.ResNet18
    num_channels: 3
    num_classes: 10
_target_: deckard.base.model.Model
trainer:
    nb_epoch: 100
    batch_size: 1024
library : pytorch
