apiVersion: v1
kind: Pod
metadata:
  name: deckard
spec:
  containers:
  - name: deckard
    image: ghcr.io/simplymathematics/deckard:pr-116
    imagePullPolicy: Always
    workingDir: /deckard/examples/sklearn
    args: ["python", "-m", "dvc", "repro"]
    env:
    - name: REDIS_HOST
      value: "redis"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_DB
      value: "0"
    - name: REDIS_PASSWORD
      value: ""
    resources:
      limits:
       nvidia.com/gpu: 1
    volumeMounts:
        - mountPath: /data
          name: mypvc
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: podpvc
