vars:
  - ../conf/plots.yaml:line_plot
  - ../conf/plots.yaml:scatter_plot
  # - ../conf/plots.yaml:cat_plot
  - ../conf/clean.yaml:attacks
  - ../conf/clean.yaml:defences
  - ../conf/clean.yaml:params
  - ../conf/clean.yaml:fillna
stages:
  # compile:
  #   foreach: # iterates through each stage
  #     - mnist
  #     - cifar
  #     - cifar100
  #     - bit_depth/mnist/
  #     - bit_depth/cifar/
  #     - bit_depth/cifar100/
  #   do:
  #     cmd: python -m deckard.layers.compile --report_folder /result/${item}/reports/attack/ --results_file raw.csv --results_folder data/${item} --config "../conf/compile.yaml"
  #     deps:
  #      - /result/${item}/reports/attack/
  #     outs:
  #     - data/${item}/raw.csv
  # get_power_data:
  #   foreach:
  #     - mnist
  #     - cifar
  #     - cifar100
  #     - bit_depth/mnist/
  #     - bit_depth/cifar/
  #     - bit_depth/cifar100/
  #   do:
  #     cmd: python -m deckard.layers.query_kepler --input_file data/${item}/raw.csv --output_file data/${item}/power.csv
  #     deps:
  #       -  data/bit_depth/${item}/raw.csv
  #       -  data/${item}/raw.csv
  #     outs:
  #       - data/${item}/power.csv
  merge:
    foreach:
       - mnist
       - cifar
       - cifar100
    do:
      cmd : python merge.py  --big_dir data/bit_depth/${item} --little_dir data/${item} --config ../conf/afr.yaml --data_file power.csv --output_folder plots/${item}/ --output_file merged.csv
      deps:
        -  data/bit_depth/${item}/power.csv
        -  data/${item}/power.csv
        - ../conf/clean.yaml
      outs:
        - plots/${item}/merged.csv
      params:
        - ../conf/clean.yaml:
          - fillna
  clean:
    foreach:
      - mnist
      - cifar
      - cifar100
    do:
      cmd: python -m deckard.layers.clean_data --i plots/${item}/merged.csv --o plots/${item}/clean.csv --config "../conf/clean.yaml"
      deps:
        - plots/${item}/merged.csv
        - ../conf/clean.yaml
      outs:
        - plots/${item}/clean.csv
      params:
        - ../conf/clean.yaml:
          - attacks
          - defences
          - params
          - fillna
  afr:
    foreach:
       - mnist
       - cifar
       - cifar100
    do:
      cmd: python -m deckard.layers.afr --dataset ${item} --data_file plots/${item}/clean.csv --config_file "../conf/afr.yaml" --plots_folder plots/${item}/ --target adv_failures --duration_col adv_fit_time
      deps:
        - plots/${item}/clean.csv
        - ../conf/afr.yaml
      plots:
        - plots/${item}/weibull_aft.pdf # You can also define them manually
        - plots/${item}/weibull_epochs_partial_effect.pdf
        - plots/${item}/cox_epochs_partial_effect.pdf
        - plots/${item}/cox_aft.pdf
        - plots/${item}/log_logistic_aft.pdf
        - plots/${item}/log_logistic_epochs_partial_effect.pdf
        - plots/${item}/log_normal_aft.pdf
        - plots/${item}/log_normal_epochs_partial_effect.pdf
      metrics:
        - plots/${item}/aft_comparison.csv
      outs:
        - plots/${item}/aft_comparison.tex
  combined_plots:
    cmd : python combined_plots.py
    deps:
      - plots/mnist/aft_comparison.csv
      - plots/cifar/aft_comparison.csv
      - plots/cifar100/aft_comparison.csv
      - combined_plots.py
    outs:
      - data/combined/combined.csv
    plots:
       - plots/combined/acc.pdf
       - plots/combined/time.pdf
       - plots/combined/cost.pdf
       - plots/combined/power.pdf
  combined_clean:
    cmd: python -m deckard.layers.clean_data --i data/combined/combined.csv --o plots/combined/clean.csv --config "../conf/clean.yaml"
    deps:
      - data/combined/combined.csv
      - ../conf/clean.yaml
    outs:
     - plots/combined/clean.csv
    params:
     - ../conf/clean.yaml:
       - attacks
       - defences
       - params
       - fillna
  combined_afr:
    cmd: python -m deckard.layers.afr --dataset Combined --data_file plots/combined/clean.csv --config_file "../conf/combined_afr.yaml" --plots_folder plots/combined/ --target adv_failures --duration_col adv_fit_time
    deps:
      - plots/combined/clean.csv
      - ../conf/combined_afr.yaml
    plots:
      - plots/combined/weibull_aft.pdf # You can also define them manually
      - plots/combined/weibull_epochs_partial_effect.pdf
      - plots/combined/weibull_batch_size_partial_effect.pdf
      - plots/combined/weibull_train_time_partial_effect.pdf
      - plots/combined/weibull_predict_time_partial_effect.pdf
      - plots/combined/weibull_attack_eps_partial_effect.pdf
      - plots/combined/cox_aft.pdf
      - plots/combined/cox_epochs_partial_effect.pdf
      - plots/combined/cox_batch_size_partial_effect.pdf
      - plots/combined/cox_train_time_partial_effect.pdf
      - plots/combined/cox_predict_time_partial_effect.pdf
      - plots/combined/cox_attack_eps_partial_effect.pdf
      - plots/combined/log_logistic_aft.pdf
      - plots/combined/log_logistic_epochs_partial_effect.pdf
      - plots/combined/log_logistic_batch_size_partial_effect.pdf
      - plots/combined/log_logistic_train_time_partial_effect.pdf
      - plots/combined/log_logistic_predict_time_partial_effect.pdf
      - plots/combined/log_logistic_attack_eps_partial_effect.pdf
      - plots/combined/log_normal_aft.pdf
      - plots/combined/log_normal_epochs_partial_effect.pdf
      - plots/combined/log_normal_batch_size_partial_effect.pdf
      - plots/combined/log_normal_train_time_partial_effect.pdf
      - plots/combined/log_normal_predict_time_partial_effect.pdf
      - plots/combined/log_normal_attack_eps_partial_effect.pdf
      
    metrics:
      - plots/combined/aft_comparison.csv
    outs:
      - plots/combined/aft_comparison.tex
