stages:
  prepare:
    cmd: 
      - python ../../deckard/layers/prepare.py  -d 'lat.csv' --target lat
    deps: 
      - configs/prepare.yml
      - ../../deckard/base/data.py
      - parsed/lat.csv
    outs: 
      - data/data.pkl
  train:
    cmd: python ../../deckard/layers/train.py  -f data -s mse -b False --name train
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yml
    - ../../deckard/layers/train.py
    - ../../deckard/base/experiment.py
    - data/data.pkl
    outs:
    - data/best_train/experiment.pkl:
        cache: true
    - data/best_train/data_params.json:
        cache: true
    - data/best_train/model_params.json:
        cache: true
    metrics:
    - data/best_train/results.json:
        cache: true
  preprocess:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s mse -b False --name preprocess --experiment best_train
    deps:
    - configs/preprocess.yml
    - ../../deckard/layers/preprocess.py
    - data/best_train/experiment.pkl
    outs:
    - data/best_preprocess/experiment.pkl:
        cache: true
    - data/best_preprocess/data_params.json:
        cache: true
    - data/best_preprocess/model_params.json:
        cache: true
    metrics:
    - data/best_preprocess/results.json:
        cache: true
  featurize:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s mse -b False --name featurize --experiment best_preprocess
    deps:
    - configs/featurize.yml
    - ../../deckard/layers/preprocess.py
    - data/best_preprocess/experiment.pkl
    outs:
    - data/best_featurize/experiment.pkl:
        cache: true
    - data/best_featurize/data_params.json:
        cache: true
    - data/best_featurize/model_params.json:
        cache: true
    metrics:
    - data/best_featurize/results.json:
        cache: true
  evaluate:
    cmd: python ../../deckard/layers/evaluate.py -f data -s mse -d "parsed/long.csv" --target "long" --experiment best_featurize
    deps: 
      - data/best_featurize/experiment.pkl
      - ./parsed/long.csv



