stages:
  prepare:
    cmd: 
      - python ../../deckard/layers/prepare.py 
    deps: 
      - configs/prepare.yaml
      - ../../deckard/base/data.py
      - parsed/gps.txt
    outs: 
      - data.pkl
  train:
    cmd: python ../../deckard/layers/sklearn_model.py --layer_name train
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yaml
    - ../../deckard/layers/sklearn_model.py
    - ../../deckard/base/experiment.py
    - data.pkl
    outs:
    - train/ :
        cache : true
  preprocess:
    cmd: python ../../deckard/layers/preprocess.py  --layer_name preprocess --position 0
    deps:
    - configs/preprocess.yaml
    - ../../deckard/layers/preprocess.py
    - train/
    outs:
    - preprocess/:
        cache: true
  featurize:
    cmd: python ../../deckard/layers/preprocess.py --layer_name featurize --position 1
    deps:
    - configs/featurize.yaml
    - ../../deckard/layers/preprocess.py
    - preprocess/
    outs:
    - featurize/:
        cache: true
  evaluate:
    cmd: python ../../deckard/layers/evaluate.py -d "parsed/gps.txt" --target "longitude" --input_folder featurize 
    deps: 
      - featurize/



