stages:
  prepare:
    cmd: 
      - python ../../deckard/layers/prepare.py  -d 'lat.csv' --target lat
    deps: 
      - configs/prepare.yml
      - ../../deckard/base/data.py
      - parsed/lat.csv
    outs: 
      - data/data.pkl
  train:
    cmd: python ../../deckard/layers/train.py  -f data -s mse -b False --name train
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yml
    - ../../deckard/layers/train.py
    - ../../deckard/base/experiment.py
    - data/data.pkl
    outs:
    - data/train/model:
        cache: true
    - data/train/data_params.json:
        cache: true
    - data/train/model_params.json:
        cache: true
    metrics:
    - data/train/scores.json:
        cache: true
  preprocess:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s mse -b False --name preprocess --input train --model_name model
    deps:
    - configs/preprocess.yml
    - ../../deckard/layers/preprocess.py
    - data/train/model
    outs:
    - data/preprocess/model:
        cache: true
    - data/preprocess/data_params.json:
        cache: true
    - data/preprocess/model_params.json:
        cache: true
    metrics:
    - data/preprocess/scores.json:
        cache: true
  featurize:
    cmd: python ../../deckard/layers/preprocess.py  -f data -s mse -b False --name featurize --input preprocess --model_name model
    deps:
    - configs/featurize.yml
    - ../../deckard/layers/preprocess.py
    - data/preprocess/model
    outs:
    - data/featurize/model:
        cache: true
    - data/featurize/data_params.json:
        cache: true
    - data/featurize/model_params.json:
        cache: true
    metrics:
    - data/featurize/scores.json:
        cache: true
  evaluate:
    cmd: python ../../deckard/layers/evaluate.py -f data -s mse -d "parsed/long.csv" --target "long" --input featurize 
    deps: 
      - data/featurize/model



