stages:
  prepare:
    cmd:
      - python ../../deckard/layers/prepare
    deps:
      - configs/prepare.yaml
      - ../../deckard/base/data.py
      - parsed/gps.txt
    params:
      - prepare
    outs:
      - data.pkl
  train:
    cmd: python -m deckard.layers.sklearn_model  train
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yaml
    - -m deckard.layers.sklearn_model.py
    - ../../deckard/base/experiment.py
    - data.pkl
    params:
      - train
    outs:
    - train/ :
        cache : true
  preprocess:
    cmd: python -m deckard.layers.preprocess  preprocess --position 0
    deps:
    - configs/preprocess.yaml
    - ../../deckard/layers/preprocess.py
    - train/
    params:
      - preprocess
    outs:
    - preprocess/:
        cache: true
  featurize:
    cmd: python -m deckard.layers.preprocess  featurize --position 1
    deps:
    - configs/featurize.yaml
    - ../../deckard/layers/preprocess.py
    - preprocess/
    params:
      - featurize
    outs:
    - featurize/:
        cache: true
  evaluate:
    cmd: python -m deckard.layers.evaluate  evaluate
    deps:
      - featurize/
    params:
      - evaluate
