stages:
  prepare:
    cmd: 
      - python ../../deckard/layers/prepare.py   --target latitude
    deps: 
      - configs/prepare.yml
      - ../../deckard/base/data.py
      - parsed/gps.txt
    outs: 
      - data/data.pkl
  train:
    cmd: python ../../deckard/layers/train.py  -f data -b False --name train -s mse
    deps:
    - ../../deckard/base/utils.py
    - configs/model.yml
    - ../../deckard/layers/train.py
    - ../../deckard/base/experiment.py
    - data/data.pkl
    outs:
    - data/train/model.pickle:
        cache: true
    - data/train/data_params.json:
        cache: true
    - data/train/model_params.json:
        cache: true
    metrics:
    - data/train/scores.json:
        cache: true
  preprocess:
    cmd: python ../../deckard/layers/preprocess.py  -f data -b False --name preprocess --input train --model_name model.pickle -s mse
    deps:
    - configs/preprocess.yml
    - ../../deckard/layers/preprocess.py
    - data/train/model.pickle
    outs:
    - data/preprocess/model.pickle:
        cache: true
    - data/preprocess/data_params.json:
        cache: true
    - data/preprocess/model_params.json:
        cache: true
    metrics:
    - data/preprocess/scores.json:
        cache: true
  featurize:
    cmd: python ../../deckard/layers/preprocess.py  -f data -b False --name featurize --input preprocess --model_name model.pickle -s mse
    deps:
    - configs/featurize.yml
    - ../../deckard/layers/preprocess.py
    - data/preprocess/model.pickle
    outs:
    - data/featurize/model.pickle:
        cache: true
    - data/featurize/data_params.json:
        cache: true
    - data/featurize/model_params.json:
        cache: true
    metrics:
    - data/featurize/scores.json:
        cache: true
  evaluate:
    cmd: python ../../deckard/layers/evaluate.py -f data -d "parsed/gps.txt" --target "longitude" --input featurize 
    deps: 
      - data/featurize/model.pickle



