data_alias: ${data.alias}
model_alias: ${oc.select:model.alias,no_model}

defaults:
  - _self_
  - data: kdd_nsl
  - model: ncd_knn
  - search/models: ${oc.select:model.alias,knn}
  - files: default
  - score: default
  - override hydra/sweeper : optuna
  - override hydra/sweeper/sampler : grid
  - override hydra/launcher : joblib

dataset: ${data_alias}
model_name: ${model_alias}
algorithm: Vanilla
attack: null
optimization: search
metric_name: gzip
fold_name: 0
study_sep: _
direction: maximize
directions:
  - ${oc.select:direction,maximize}
optimizers:
  - accuracy
device: ${oc.env:DECKARD_DEVICE_ID, "cpu"}

hydra:
  run:
    dir: output/logs/${hydra.sweeper.study_name}
  sweep:
    dir: output/logs/
    subdir: ${hydra.sweeper.study_name}/${hydra.job.num}
  callbacks:
    deckard_optuna:
      _target_: deckard.layers.optimize.DefaultOptimizerCallback
      directions: ${directions}
      optimizers: ${optimizers}
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: ${oc.select:direction,maximize}
    storage: sqlite:///output/optuna.db
    study_name: ${oc.select:optimization,search}${oc.select:study_sep,_}${oc.select:dataset,unknown_dataset}${oc.select:study_sep,_}${oc.select:model_name,no_model}${oc.select:study_sep,_}${oc.select:algorithm,Vanilla}${oc.select:study_sep,_}${oc.select:metric_name,gzip}${oc.select:study_sep,_}${oc.select:data.sampler.train_size,1000}${oc.select:study_sep,_}${oc.select:fold_name,0}
    n_trials: 1
    n_jobs: 1
    max_failure_rate: 1.0
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 1
    prefer: processes
    verbose: 1
    timeout: ${oc.env:DECKARD_TIMEOUT, 1800}
    pre_dispatch: 2*${hydra.sweeper.n_jobs}
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
