stages:
  prepare:
    cmd: python -m deckard.layers.prepare.py
    params:
      - prepare
    outs: 
      - data.pkl
  control:
    cmd:  python -m deckard.layers.art_model  control
    deps:
    - data.pkl
    params:
    - control
    outs:
    - control/:
        cache: true
  defend:
    cmd:  python -m deckard.layers.defend  defend
    deps:
    - data.pkl
    - control/control_model.pb
    - configs/defence_config.yaml
    params:
    - defend
    outs:
    - defences/:
        cache: true
  attack:
    cmd:  python -m deckard.layers.attack  attack
    deps:
    - data.pkl
    - defences/defended_model
    - configs/attack_config.yaml
    params:
    - attack
    outs:
    - attacks/:
        cache: true





