stages:
  prepare:
    cmd: python ../../deckard/layers/prepare.py
    params:
      - prepare
    outs: 
      - data.pkl
  control:
    cmd:  python ../../deckard/layers/art_model.py --layer_name control
    deps:
    - data.pkl
    params:
    - control
    outs:
    - control/:
        cache: true
  defend:
    cmd:  python ../../deckard/layers/defend.py --layer_name defend
    deps:
    - data.pkl
    - control/control_model.pb
    - configs/defence_config.yaml
    params:
    - defend
    outs:
    - defences/:
        cache: true
  attack:
    cmd:  python ../../deckard/layers/attack.py --layer_name attack
    deps:
    - data.pkl
    - defences/defended_model
    - configs/attack_config.yaml
    params:
    - attack
    outs:
    - attacks/:
        cache: true





