stages:
  generate_data:
    cmd: python -m deckard.layers.runner --stage generate_data
    params:
      - data
      - files
    outs:
      - ${files.data_file}
      - ${files.reports}/generate_data/${files.path}
  train:
    cmd: python -m deckard.layers.runner --stage train
    params:
      - data
      - model
      - files
      - scorers
    deps:
      - ${files.data_file}
    outs:
      # - ${files.model_file}
      - ${files.reports}/train/${files.path}
