data:
  generate:
    class_sep: 1
    n_classes: 2
    n_features: 100
    n_informative: 99
    n_redundant: 0
    n_repeated: 0
    n_samples: 101000
  name: classification
  sample:
    random_state: 42
    shuffle: true
    stratify: true
    test_size: 1000
    time_series: true
    train_size: 1000
files:
  attack_predictions_file: attack_predictions.json
  attack_probabilities_file: attack_probabilities.json
  attack_samples_file: samples.json
  attack_score_dict_file: attack_scores.json
  attack_time_dict_file: attack_time_dict.json
  data_file: data/ad5713b7391bfb03f94e026cc3cf6421.npz
  ground_truth_file: ground_truth.json
  model_file: models/30fa77b58d17ae4463cf12591d8f3968.pkl
  params_file: params.json
  path: 6f5cea2ad9f3567f1d5bf4e9c8b6cba5
  predictions_file: predictions.json
  probabilities_file: probabilities.json
  reports: reports
  score_dict_file: scores.json
  time_dict_file: time_dict.json
model:
  init:
    name: sklearn.linear_model.SGDRegressor
plots:
  balance: balance
  classification: classification
  confusion: confusion
  correlation: correlation
  radviz: radviz
  rank: rank
scorers:
  mape:
    name: sklearn.metrics.mean_absolute_percentage_error
  mse:
    name: sklearn.metrics.mean_squared_error
  r2:
    name: sklearn.metrics.r2_score
