_target_: deckard.score.ScorerDictConfig
scorers:
  accuracy:
    score_name: accuracy
    score_function: sklearn.metrics.accuracy_score
    greater_is_better: true
    needs_proba: false
  log_loss:
    score_name: log_loss
    score_function: sklearn.metrics.log_loss
    greater_is_better: false
    needs_proba: false
