- name: art.defences.preprocessor.FeatureSqueezing
  params:
    clip_values : !!python/tuple [0,255]
    bit_depth : 4
    # [4, 8, 16, 32, 64]

# - name: art.defences.preprocessor.GaussianAugmentation
#   params:
#     clip_values : !!python/tuple [0,255]
#     sigma : [.1, .3, 1]
#     ratio : [.1, .5, 1]

# - name: art.defences.preprocessor.SpatialSmoothing
#   params:
#     clip_values : !!python/tuple [0,255]
#     window_size : [2,3,4]

# - name: art.defences.preprocessor.TotalVarMin
#   params:
#     clip_values : !!python/tuple [0,255]
#     prob : [.001, .01, .1]
#     norm : [1, 2, 3]
#     lamb : [.05, .5, .95]
#     max_iter : [100]

# - name : art.defences.postprocessor.ClassLabels
#   params:
#     apply_predict : [True]
#     apply_fit : [False]

# - name : art.defences.postprocessor.GaussianNoise
#   params:
#     scale: [.1, .9, .999]

# - name : art.defences.postprocessor.HighConfidence
#   params:
#     cutoff : [.1, .5, .9, .99]

# - name : art.defences.postprocessor.ReverseSigmoid
#   params:
#     beta : [1, 10 , 100]
#     gamma : [.1, 1, 10, 100]

# - name : art.defences.postprocessor.Rounded
#   params:
#     decimals : [1, 2, 4, 8]
