defaults:
  - _self_
  - defense: null

name: deckard.frameworks.transformers.declarations.PretrainedSequenceClassificationTransformer
model_params:
  model_name: distilbert/distilbert-base-uncased-finetuned-sst-2-english
  model_revision: main
  pretrained: true
  num_classes: 2
  return_features: false

classifier: true
_target_: deckard.frameworks.transformers.model.HuggingFacePytorchModelConfig
fit_params:
  nb_epochs: 0
  batch_size: 16
  verbose: false
library: pytorch
criterion: CrossEntropyLoss
optimizer:
  name: SGD
  lr: 0.01
  momentum: 0.9
clip_values: [0, 1]
alias: hf_distilbert_sst2_tuned
