model_type: deckard.pytorch.model.TinyNet
classifier: true
model_params:
  input_dim: 10  # Set default, should be overridden by data shape
  hidden_dim: 16
  output_dim: 2
_target_: deckard.pytorch.model.PytorchModelConfig
alias: tinynet
