model_type: torch_example.ResNet18
model_params:
    num_channels: 1 # For grayscale images like MNIST
    num_classes: 10 # Number of classes in the dataset
classifier : True
_target_ : deckard.model.pytorch.PytorchModelConfig
fit_params:
  nb_epochs: 1
  batch_size: 1024
  verbose: True
library : pytorch
criterion: CrossEntropyLoss
optimizer:
    name : SGD
    lr : 0.01
    momentum : 0.9
clip_values : [0, 255]
alias: torch_resnet18