stages:
  # notebook_deckard:
  #   cmd: >
  #     mkdir -p build/notebook_artifacts && if [[ ! -s deckard.ipynb ]]; then echo '{"cells": [], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}' > build/notebook_./build/deckard.executed.ipynb; else python -m jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 --output deckard.executed.ipynb --output-dir build/notebook_artifacts deckard.ipynb; fi
  #   deps:
  #     - deckard.ipynb
  #     - .deckard/__main__.py
  #     - .deckard/experiment/
  #     - .deckard/file.py
  #     - .deckard/utils.py
  #   outs:
  #     - ./build/notebook_./build/deckard.executed.ipynb

  # notebook_hydra:
  #   cmd: >
  #     mkdir -p build/notebook_artifacts && if [[ ! -s hydra.ipynb ]]; then echo '{"cells": [], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}' > build/notebook_./build/hydra.executed.ipynb; else python -m jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 --output hydra.executed.ipynb --output-dir build/notebook_artifacts hydra.ipynb; fi
  #   deps:
  #     - hydra.ipynb
  #     - .deckard/__main__.py
  #     - .deckard/experiment/
  #     - .deckard/file.py
  #     - .deckard/utils.py
  #   outs:
  #     - ./build/notebook_./build/hydra.executed.ipynb

  notebook_seaborn:
    cmd: jupyter nbconvert --to notebook --execute --inplace seaborn.ipynb
    deps:
      - seaborn.ipynb
      - ../../deckard/plot/seaborn_plots.py
      - ../../deckard/plot/declarations.py
      - ../../deckard/plot/__init__.py
    plots:
      - ./build/seaborn/bar_bar_plot_from_make_blobs.png
      - ./build/seaborn/cat_categorical_plot_from_make_moons.png
      - ./build/seaborn/heatmap_heatmap_from_make_classification_correlations.png
      - ./build/seaborn/hist_histogram_plot_from_make_friedman1.png
      - ./build/seaborn/line_line_plot_from_make_regression.png
      - ./build/seaborn/scatter_scatter_plot_from_make_classification.png
  notebook_yellowbrick:
    cmd: jupyter nbconvert --to notebook --execute --inplace yellowbrick.ipynb
    deps:
      - yellowbrick.ipynb
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/experiment/
      - ../../deckard/file.py
      - ../../deckard/plot/yellowbrick_plots.py
      - ../../deckard/plot/declarations.py
      - ../../deckard/plot/__init__.py
    outs:
      - ./build/yellowbrick/plots/all_types_balanced_binning_reference.png
      - ./build/yellowbrick/plots/all_types_class_balance.png
      - ./build/yellowbrick/plots/all_types_class_prediction_error.png
      - ./build/yellowbrick/plots/all_types_classification_report.png
      - ./build/yellowbrick/plots/all_types_cv_scores.png
      - ./build/yellowbrick/plots/all_types_discrimination_threshold.png
      - ./build/yellowbrick/plots/all_types_dropping_curve.png
      - ./build/yellowbrick/plots/all_types_feature_correlation.png
      - ./build/yellowbrick/plots/all_types_feature_importances.png
      - ./build/yellowbrick/plots/all_types_intercluster_distance.png
      - ./build/yellowbrick/plots/all_types_jointplot.png
      - ./build/yellowbrick/plots/all_types_k_elbow.png
      - ./build/yellowbrick/plots/all_types_learning_curve.png
      - ./build/yellowbrick/plots/all_types_pca.png
      - ./build/yellowbrick/plots/all_types_pcoords.png
      - ./build/yellowbrick/plots/all_types_precision_recall_curve.png
      - ./build/yellowbrick/plots/all_types_prediction_error.png
      - ./build/yellowbrick/plots/all_types_radviz.png
      - ./build/yellowbrick/plots/all_types_rank1d.png
      - ./build/yellowbrick/plots/all_types_rank2d.png
      - ./build/yellowbrick/plots/all_types_residuals_plot.png
      - ./build/yellowbrick/plots/all_types_rfecv.png
      - ./build/yellowbrick/plots/all_types_roc_auc.png
      - ./build/yellowbrick/plots/all_types_silhouette.png
      - ./build/yellowbrick/plots/all_types_validation_curve.png
      - ./build/yellowbrick/plots/torch_classification_report.png
      - ./build/yellowbrick/plots/torch_precision_recall_curve.png
      - ./build/yellowbrick/plots/torch_roc_auc.png
      - ./build/yellowbrick/plots/plotlist_demo/class_balance.png
      - ./build/yellowbrick/plots/plotlist_demo/classification_report.png
      - ./build/yellowbrick/plots/plotlist_demo/precision_recall_curve.png
      - ./build/yellowbrick/plots/plotlist_demo/rank1d.png
      - ./build/yellowbrick/plots/plotlist_demo/roc_auc.png

  notebook_detector:
    cmd: jupyter nbconvert --to notebook --execute detector.ipynb
    deps:
      - detector.ipynb
      - ../../deckard/attack/
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    metrics:
      - ./build/detector/canonical_attack_examples.csv
  notebook_art_attacks:
    cmd: jupyter nbconvert --to notebook --execute --inplace art_attacks.ipynb
    deps:
      - art_attacks.ipynb
      - ../../deckard/attack/
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    plots:
      - ./build/art_attacks/plot.png
    outs:
      - ./build/art_attacks/sklearn_data.pkl
      - ./build/art_attacks/sklearn_attribute_attack.pkl
      - ./build/art_attacks/hsj_evasion_attack_file.pkl
      - ./build/art_attacks/fgm_evasion_attack_file.pkl 
      - ./build/art_attacks/boundary_evasion_attack_file.pkl 
      - ./build/art_attacks/sklearn_membership_attack.pkl
      - ./build/art_attacks/sklearn_model.pkl
      - ./build/art_attacks/svm.pkl
      - ./build/art_attacks/torch_evasion_attack.pkl
      - ./build/art_attacks/torch_model.pt
      - ./build/art_attacks/torch_extraction_model.pt
    metrics:
      - ./build/art_attacks/membership_scores.csv
      - ./build/art_attacks/torch_scores.csv
      - ./build/art_attacks/sklearn_scores.csv
  notebook_art_defenses:
    cmd: jupyter nbconvert --to notebook --execute art_defenses.ipynb
    deps:
      - art_defenses.ipynb
      - ../../deckard/attack/
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    metrics:
      - ./build/art_defenses/defense_chain_order.csv
      - ./build/art_defenses/defense_chain_result.csv
      - ./build/art_defenses/sklearn_defense_results.csv
      - ./build/art_defenses/torch_defense_results.csv

  notebook_sklearn:
    cmd: jupyter nbconvert --to notebook --execute --inplace sklearn.ipynb
    deps:
      - sklearn.ipynb
      - ../../deckard/attack/
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/detector/
      - ../../deckard/experiment/
      - ../../deckard/score/
      - ../../deckard/plot/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    outs: 
      - ./build/sklearn/experiment_data_lr.pkl
      - ./build/sklearn/experiment_model_lr.pkl
    metrics:
      - ./build/sklearn/experiment_scores_lr.json
      - ./build/sklearn/seaborn_results.csv
    plots:
      - ./build/sklearn/plots/seaborn_line.png
      - ./build/sklearn/plots/seaborn_scatter.png
      - ./build/sklearn/plots/yellowbrick_roc_auc.png

  notebook_pytorch:
    cmd: jupyter nbconvert --to notebook --execute --inplace pytorch.ipynb
    deps:
      - pytorch.ipynb
      - ../../deckard/attack/
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/experiment/
      - ../../deckard/score/
      - ../../deckard/plot/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    metrics:
      - ./build/pytorch/pytorch_results.csv
    plots:
      - ./build/pytorch/plots/pytorch_line.png
      - ./build/pytorch/plots/pytorch_roc_auc.png
      - ./build/pytorch/plots/pytorch_scatter.png 
    outs:
      - ./build/pytorch/exp_model.pt
      - ./build/pytorch/checkpoints/
      - ./build/pytorch/raw_data/
  notebook_fairlearn:
    cmd: jupyter nbconvert --to notebook --execute --inplace fairlearn.ipynb
    deps:
      - fairlearn.ipynb
      - ../../deckard/attack/
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/experiment/
      - ../../deckard/score/
      - ../../deckard/plot/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    outs:
      - ./build/fairlearn/fairlearn_data.pkl
      - ./build/fairlearn/fairlearn_fair_data.pkl
      - ./build/fairlearn/fairlearn_sklearn_model.pkl
      - ./build/fairlearn/fairlearn_torch_model.pt
      - ./build/fairlearn/fairlearn_sklearn_scores.csv
      - ./build/fairlearn/fairlearn_torch_scores.csv
      - ./build/fairlearn/fairlearn_attack_results.pkl
    plots:
      - ./build/fairlearn/fairlearn_attack_plot.png
      - ./build/fairlearn/fairlearn_roc_auc.png
      - ./build/fairlearn/fairlearn_sklearn_compare_bar.png
      - ./build/fairlearn/fairlearn_torch_compare_bar.png
      - /build/fairlearn/plots/
    metrics:
      - ./build/fairlearn/fairlearn_model_compare.csv
      - ./build/fairlearn/fairlearn_sklearn_compare.csv
      - ./build/fairlearn/fairlearn_torch_compare.csv

  notebook_anjana:
    cmd: jupyter nbconvert --to notebook --execute --inplace anjana.ipynb
    deps:
      - anjana.ipynb
      - ../../deckard/data/
      - ../../deckard/model/
      - ../../deckard/attack/
      - ../../deckard/experiment/
      - ../../deckard/score/
      - ../../deckard/plot/
      - ../../deckard/file.py
      - ../../deckard/utils.py
    outs:
      - ./build/anjana/anjana_attack_baseline.pkl
      - ./build/anjana/anjana_attack_defended.pkl
      - ./build/anjana/anjana_baseline_data.pkl
      - ./build/anjana/anjana_baseline_sklearn_model.pkl
      - ./build/anjana/anjana_defended_data.pkl
      - ./build/anjana/anjana_defended_sklearn_model.pkl
      - ./build/anjana/baseline_experiment_data.pkl
      - ./build/anjana/baseline_experiment_model.pkl
      - ./build/anjana/defended_experiment_data.pkl
    metrics:
      - ./build/anjana/anjana_baseline_scores.csv
      - ./build/anjana/anjana_data_scores_compare.csv
      - ./build/anjana/anjana_defended_scores.csv
      - ./build/anjana/baseline_experiment_scores.json
      - ./build/anjana/defended_experiment_scores.json
    plots:
      - ./build/anjana/plots/anjana_attack_compare_bar.png
      - ./build/anjana/plots/anjana_data_compare_bar_side_by_side.png
      - ./build/anjana/plots/anjana_data_scores_bar.png
      - ./build/anjana/plots/anjana_yellowbrick_roc_auc.png

  # notebook_lifelines:
  #   cmd: >
  #     mkdir -p build/notebook_artifacts && if [[ ! -s lifelines.ipynb ]]; then echo '{"cells": [], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}' > build/notebook_./build/lifelines.executed.ipynb; else python -m jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 --output lifelines.executed.ipynb --output-dir build/notebook_artifacts lifelines.ipynb; fi
  #   deps:
  #     - lifelines.ipynb
  #     - .deckard/data/survival.py
  #     - .deckard/model/survival.py
  #     - .deckard/experiment/survival.py
  #     - .deckard/score/survival.py
  #     - .deckard/plot/survival.py
  #     - .deckard/file.py
  #     - .deckard/utils.py
  #   outs:
  #     - ./build/notebook_./build/lifelines.executed.ipynb