ground_truth_file: ground_truth.json
params_file: params.json
reports: reports
path : ""
predictions_file: predictions.json
score_dict_file: scores.json
time_dict_file: time_dict.json
probabilities_file : probabilities.json
samples_file : samples.json