data:
  _target_: deckard.base.data.Data
  drop:
  - BotScore
  name: https://gist.githubusercontent.com/simplymathematics/8c6c04bd151950d5ea9e62825db97fdd/raw/34e546e4813f154d11d4f13869b9e3481fc3e829/truthseeker.csv
  sample:
    random_state: 0
    stratify: true
    test_size: 100
    train_size: 2000
  sklearn_pipeline:
    encoder:
      handle_unknown: use_encoded_value
      name: sklearn.preprocessing.OrdinalEncoder
      unknown_value: -1
    preprocessor:
      name: sklearn.preprocessing.StandardScaler
      with_mean: true
      with_std: true
  target: BotScoreBinary
dataset: truthseeker
device_id: cpu
direction:
- maximize
files:
  _target_: deckard.base.files.FileConfig
  data_dir: data
  directory: truthseeker
  model_dir: model
  name: default
  params_file: params.yaml
  predictions_file: predictions.json
  reports: reports
  score_dict_file: score_dict.json
model:
  _target_: deckard.base.model.Model
  art:
    _target_: deckard.base.model.art_pipeline.ArtPipeline
    initialize:
      nb_classes: 3
    library: sklearn
  data:
    _target_: deckard.base.data.Data
    drop:
    - BotScore
    name: https://gist.githubusercontent.com/simplymathematics/8c6c04bd151950d5ea9e62825db97fdd/raw/34e546e4813f154d11d4f13869b9e3481fc3e829/truthseeker.csv
    sample:
      random_state: 0
      stratify: true
      test_size: 100
      train_size: 2000
    sklearn_pipeline:
      encoder:
        handle_unknown: use_encoded_value
        name: sklearn.preprocessing.OrdinalEncoder
        unknown_value: -1
      preprocessor:
        name: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true
    target: BotScoreBinary
  init:
    _target_: deckard.base.model.ModelInitializer
    compressor: gzip
    distance_matrix: truthseeker/model/gzip_classifier/gzip/0-2000.npz
    k: 1
    m: -1
    method: random
    name: gzip_classifier.GzipClassifier
  library: sklearn
model_name: gzip_classifier
optimizers:
- accuracy
scorers:
  _target_: deckard.base.scorer.ScorerDict
  accuracy:
    _target_: deckard.base.scorer.ScorerConfig
    direction: maximize
    name: sklearn.metrics.accuracy_score
  log_loss:
    _target_: deckard.base.scorer.ScorerConfig
    direction: minimize
    name: sklearn.metrics.log_loss
stage: train
