data:
  _target_: deckard.base.data.Data
  name: https://gist.githubusercontent.com/simplymathematics/8c6c04bd151950d5ea9e62825db97fdd/raw/d6a22cdb42a1db624c89f0298cb4f654d3812703/kdd_nsl.csv
  sample:
    _target_: deckard.base.data.SklearnDataSampler
    random_state: 0
    stratify: true
    test_size: 100
    train_size: 100
  sklearn_pipeline:
    encoder:
      handle_unknown: use_encoded_value
      name: sklearn.preprocessing.OrdinalEncoder
      unknown_value: -1
    preprocessor:
      name: sklearn.preprocessing.StandardScaler
      with_mean: true
      with_std: true
  target: label
dataset: kdd_nsl
device_id: cpu
direction:
- maximize
files:
  _target_: deckard.base.files.FileConfig
  data_dir: data
  data_type: .csv
  directory: kdd_nsl
  model_dir: model
  name: default
  params_file: params.yaml
  predictions_file: predictions.json
  reports: reports
  score_dict_file: score_dict.json
model:
  _target_: deckard.base.model.Model
  art:
    _target_: deckard.base.model.art_pipeline.ArtPipeline
    initialize:
      nb_classes: 2
    library: sklearn
  data:
    _target_: deckard.base.data.Data
    name: https://gist.githubusercontent.com/simplymathematics/8c6c04bd151950d5ea9e62825db97fdd/raw/d6a22cdb42a1db624c89f0298cb4f654d3812703/kdd_nsl.csv
    sample:
      _target_: deckard.base.data.SklearnDataSampler
      random_state: 0
      stratify: true
      test_size: 100
      train_size: 100
    sklearn_pipeline:
      encoder:
        handle_unknown: use_encoded_value
        name: sklearn.preprocessing.OrdinalEncoder
        unknown_value: -1
      preprocessor:
        name: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true
    target: label
  init:
    _target_: deckard.base.model.ModelInitializer
    compressor: gzip
    distance_matrix: kdd_nsl/model/gzip_classifier/gzip/0-100.npz
    k: 1
    m: -1
    method: null
    metric: ncd
    name: gzip_classifier.GzipClassifier
    symmetric: true
  library: sklearn
model_name: gzip_classifier
optimizers:
- accuracy
scorers:
  _target_: deckard.base.scorer.ScorerDict
  accuracy:
    _target_: deckard.base.scorer.ScorerConfig
    direction: maximize
    name: sklearn.metrics.accuracy_score
  log_loss:
    _target_: deckard.base.scorer.ScorerConfig
    direction: minimize
    name: sklearn.metrics.log_loss
stage: train
