data:
  _target_: deckard.base.data.Data
  name: raw_data/kdd_nsl.csv
  sample:
    _target_: deckard.base.data.SklearnDataSampler
    random_state: 0
    stratify: true
    test_size: 10
    train_size: 10
  target: label
dataset: kdd_nsl
device_id: cpu
direction:
- maximize
files:
  _target_: deckard.base.files.FileConfig
  data_dir: data
  data_type: .csv
  directory: kdd_nsl
  model_dir: model
  name: default
  params_file: params.yaml
  predictions_file: predictions.json
  reports: reports
  score_dict_file: score_dict.json
model:
  _target_: deckard.base.model.Model
  art:
    _target_: deckard.base.model.art_pipeline.ArtPipeline
    initialize:
      nb_classes: 2
    library: sklearn
  data:
    _target_: deckard.base.data.Data
    name: raw_data/kdd_nsl.csv
    sample:
      _target_: deckard.base.data.SklearnDataSampler
      random_state: 0
      stratify: true
      test_size: 10
      train_size: 10
    target: label
  init:
    _target_: deckard.base.model.ModelInitializer
    distance_matrix: kdd_nsl/model/gzip_knn/gzip/10-0.npz
    k: 1
    m: -1
    metric: gzip
    name: gzip_classifier.GzipKNN
    symmetric: false
  library: sklearn
model_name: gzip_knn
optimizers:
- accuracy
scorers:
  _target_: deckard.base.scorer.ScorerDict
  accuracy:
    _target_: deckard.base.scorer.ScorerConfig
    direction: maximize
    name: sklearn.metrics.accuracy_score
  log_loss:
    _target_: deckard.base.scorer.ScorerConfig
    direction: minimize
    name: sklearn.metrics.log_loss
stage: train
