
attack_type : "art.attacks.evasion.CarliniL2Method"
attack_params : 
  batch_size: 2
  max_iter: 1
  confidence: .99
  verbose: false
  binary_search_steps : 1
  max_halving: 1
  max_doubling: 1 
attack_size : 4
_target_ : deckard.attack.AttackConfig
alias: carlini_l2
