# python -m deckard.layers.optimise +attack.init.name=art.attacks.evasion.DeepFool +attack.init.max_iter=10 +attack.init.batch_size=100 +attack.init.nb_grads=10,100,1000 +stage=attack --multirun
attack_type : "art.attacks.evasion.DeepFool"
attack_params : 
  max_iter: 10
  batch_size: 100
  nb_grads: 10
_target_ : deckard.attack.AttackConfig
alias: deepfool
