attack_type : "art.attacks.evasion.FastGradientMethod"
attack_params : 
  eps_step: .01
  norm: inf
  targeted: False
  eps: 1
  minimal : False
  batch_size : ${model.fit_params.batch_size}
_target_ : deckard.attack.AttackConfig
alias: fgm
