apiVersion: v1
kind: Pod
metadata:
  name: nvidia-tesla-p100-cifar10
spec:
  containers:
  - name: deckard
    image: ghcr.io/simplymathematics/deckard:main
    imagePullPolicy: Always
    workingDir: /deckard/examples/power/
    args: ["python", "-m", "deckard", "--config_file", "cifar10.yaml"]
    env:
    - name: DECKARD_DEVICE
      value: nvidia-tesla-p100
    # - name: REDIS_HOST
    #   value: "redis"
    # - name: REDIS_PORT
    #   value: "6379"
    # - name: REDIS_DB
    #   value: "0"
    # - name: REDIS_PASSWORD
    #   value: ""
    resources:
      limits:
       nvidia.com/gpu: 1
    volumeMounts:
        - mountPath: /deckard/
          name: mypvc
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: podpvc
