attack_type : "art.attacks.inference.membership_inference.MembershipInferenceBlackBox"
attack_size : 100
init_params:
  library: art
  type: inference
  class: MembershipInferenceBlackBox
attack_params:
  attack_model: ${model}
_target_ : deckard.attack.AttackConfig
alias: membership
