_target_: deckard.file.FileConfig
data_file: result/bit_depth/cifar100/data/data.pkl
attack_file: result/bit_depth/cifar100/attacks/attack.pkl
score_file: result/bit_depth/cifar100/reports/attack/score_dict.json
params_file: result/bit_depth/cifar100/params.yaml
test_predictions_file: result/bit_depth/cifar100/reports/attack/predictions.json
attack_predictions_file: result/bit_depth/cifar100/reports/attack/adv_predictions.json
log_file: result/bit_depth/cifar100/reports/logs/run.log
error_file: result/bit_depth/cifar100/reports/logs/error.log
