defaults:
  - default
  - data: kdd_nsl
  - model: ncd_logistic
  - data/pipeline: logistic
  - search/models: logistic
defaults:
  - default
  - data: kdd_nsl
  - model: ncd_knn
  - data/pipeline: knn
  - search/models: knn
