stages:
  install_deckard:
    cmd: python -m pip install -e ../../ && python -m pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    deps:
      - ../../setup.py
    outs:
      - ../../deckard.egg-info:
          cache: False
          persist: True
  # install_redis:
  #   cmd: bash redis.sh
  #   outs: 
  #     - .bashrc
  #   # params:
  #   #  - oc.
  parse_params:
    cmd: python -m deckard.layers.parse --config_file ${data.generate.name}.yaml
    deps:
      - conf/
      - ../../deckard.egg-info
    outs:
      - params.yaml:
          cache: True
          persist: True
  train:
    cmd: python -m deckard.layers.experiment train --config_file ${data.generate.name}.yaml
    params:
      - data
      - model
      - scorers
      - files
      - device_id
    # outs:
      # - ${files.directory}/${files.data_dir}/${files.data_file}${files.data_type}
      # - ${files.directory}/${files.model_dir}/${files.model_file}${files.model_type}
      # - ${files.directory}/${files.model_dir}/${files.model_file}.optimizer${files.model_type}
      # - ${files.directory}/${files.reports}/train/${files.name}/${files.score_dict_file}
      # - ${files.directory}/${files.reports}/train/${files.name}/${files.test_labels_file} # Omit to save space
      # - ${files.directory}/${files.reports}/train/${files.name}/${files.predictions_file}  # logit outputs for our model
      # - ${files.directory}/${files.reports}/train/${files.name}/${files.probabilities_file} # Omit to save space
    metrics:
      - ${files.directory}/${files.reports}/train/${files.name}/${files.score_dict_file}:
          cache : false
  attack:
    cmd: python -m deckard.layers.experiment attack --config_file ${data.generate.name}.yaml
    params:
      - data
      - model
      - attack
      - scorers
      - files
      - device_id
    outs:
      - ${files.directory}/${files.attack_dir}/${files.attack_file}${files.attack_type}:
          cache : false
      - ${files.directory}/${files.reports}/attack/${files.name}/${files.adv_predictions_file}:
          cache : false
      - ${files.directory}/${files.data_dir}/${files.data_file}${files.data_type}:
          cache : false
      - ${files.directory}/${files.reports}/attack/${files.name}/${files.predictions_file}:  # logit outputs for our model
          cache : false 
    deps:
        - params.yaml
    metrics:
      - ${files.directory}/${files.reports}/attack/${files.name}/${files.score_dict_file}:
          cache: false
  attacks:
    cmd: python -m deckard.layers.optimise  --multirun ++attack.attack_size=100 stage=attack ++hydra.sweeper.storage=sqlite:///${files.directory}/${device_id}.db  --config-name ${data.generate.name}.yaml
    deps:
      - ${files.directory}/${files.reports}/attack/${files.name}/${files.score_dict_file} # This is here just to ensure it runs after the attack stage
    outs:
       # This outputs a database file for each model
      - ${files.directory}/${data.generate.name}.db:
          cache: false
