# - name: sklearn.ensemble.RandomForestRegressor
#   params:
#     'n_estimators' : [10, 50, 100]

- name: sklearn.neighbors.KNeighborsRegressor
  params:
    'n_neighbors' : [1,3, 10]
    'weights' : ['uniform', 'distance']
