_target_: deckard.file.FileConfig
data_file: output/${dataset}/data/${dataset}-${data.random_state}-${data.train_size}-${data.test_size}-${oc.select:data.split,0}.pkl
score_file: output/${dataset}/reports/precompute/score_dict.json
params_file: output/${dataset}/params.yaml
test_predictions_file: output/${dataset}/reports/precompute/predictions.json
log_file: output/${dataset}/reports/logs/run.log
error_file: output/${dataset}/reports/logs/error.log
