data: ${data}
library : sklearn
init:
    _target_: deckard.base.model.ModelInitializer
    name : gzip_classifier.GzipLogisticRegressor
    m: -1
    metric : gzip
    symmetric : false
_target_: deckard.base.model.Model