data: ${data}
library : sklearn
init:
    _target_: deckard.base.model.ModelInitializer
    name : gzip_classifier.GzipSVC
    m: -1
    distance_matrix : 
    metric : gzip
    symmetric : false
_target_: deckard.base.model.Model