data: ${data}
library : sklearn
init:
    _target_: deckard.base.model.ModelInitializer
    name : gzip_classifier.GzipKNN
    k : 1
    m: -1
    method : null
    distance_matrix : 
    metric : gzip
    symmetric : false
_target_: deckard.base.model.Model
art:
    _target_ : deckard.base.model.art_pipeline.ArtPipeline
    library : sklearn
    initialize:
        nb_classes : 2