data: ${data}
library : sklearn
init:
    _target_: deckard.base.model.ModelInitializer
    name : gzip_classifier.GzipClassifier
    k : 1
    m: -1
    method : null
    distance_matrix : ${files.directory}/${files.model_dir}/${model_name}/${model.init.compressor}/${data.sample.random_state}-${data.sample.train_size}.npz
    compressor : gzip
_target_: deckard.base.model.Model
art:
    _target_ : deckard.base.model.art_pipeline.ArtPipeline
    library : sklearn
    initialize:
        nb_classes : 2