data: ${data}
library : sklearn-svc
init:
    _target_: deckard.base.model.ModelInitializer
    name : sklearn.svm.SVC
    C : float(.001, .01, .1, 1, 10, 100, 1000)
    kernel : linear
    probability : true
    random_state : 0
    max_iter : 100
_target_: deckard.base.model.Model
art:
    _target_ : deckard.base.model.art_pipeline.ArtPipeline
    library : sklearn-svc
    initialize:
