vars:
  - plots.yaml:cat_plot
  - plots.yaml:line_plot
  - plots.yaml:scatter_plot
  - afr.yaml:covariates
  - afr.yaml:weibull
  - afr.yaml:log_logistic
  - afr.yaml:log_normal
  # - afr.yaml:gamma
  # - afr.yaml:exponential
  - afr.yaml:cox
stages:
  clean:
    foreach:
      - cifar
      - cifar100
      - mnist
    do:
      cmd: >-
        python -m deckard.layers.clean_data
        -i data/attack_${item}.csv 
        -o data/${item}.csv 
        -c ../conf/clean_${item}.yaml
        --drop_if_empty adv_fit_time accuracy train_time predict_time adv_accuracy Epochs
      deps:
        - data/attack_${item}.csv
        - ../conf/clean_${item}.yaml
      outs:
        - data/${item}.csv
  merge:
    deps:
      - data/mnist.csv
      - data/cifar.csv
      - data/cifar100.csv
    cmd: >-
      python -m deckard.layers.merge
      --smaller_file data/cifar.csv data/cifar100.csv data/mnist.csv 
      --output_folder data
      --output_file merged.csv
    outs:
      -  data/merged.csv
  plot:
    cmd : python -m deckard.layers.plots --path plots/ --file data/merged.csv -c plots.yaml
    deps:
      - data/merged.csv
      - plots.yaml
    plots:
      - plots/${cat_plot[0].file}
      - plots/${cat_plot[1].file}
      - plots/${cat_plot[2].file}
      - plots/${cat_plot[3].file}
      - plots/${cat_plot[4].file}
      - plots/${cat_plot[5].file}
      - plots/${cat_plot[6].file}
      - plots/${cat_plot[7].file}
      - plots/${line_plot[0].file}
      - plots/${line_plot[1].file}
      - plots/${line_plot[2].file}
      - plots/${line_plot[3].file}
      - plots/${scatter_plot[0].file}
    params:
      - plots.yaml:
        - line_plot
        - scatter_plot
        - cat_plot
  afr:
    cmd: python -m deckard.layers.afr  --data_file data/merged.csv  --target adv_failures --duration_col adv_fit_time  --config_file afr.yaml --plots_folder plots/
    deps:
      - data/merged.csv
    plots:
      - plots/weibull_aft.pdf
      - plots/weibull_aft_dummies.pdf
      - plots/weibull_summary.csv
      - plots/weibull_qq.pdf
      - plots/log_logistic_aft.pdf
      - plots/log_logistic_aft_dummies.pdf
      - plots/log_logistic_qq.pdf
      - plots/log_logistic_summary.csv
      - plots/log_normal_aft.pdf
      - plots/log_normal_aft_dummies.pdf
      - plots/log_normal_qq.pdf
      - plots/log_normal_summary.csv
      - plots/gamma_aft.pdf
      - plots/gamma_aft_dummies.pdf
      - plots/gamma_qq.pdf
      - plots/gamma_summary.csv
      - plots/exponential_aft.pdf
      - plots/exponential_aft_dummies.pdf
      - plots/exponential_qq.pdf
      - plots/exponential_summary.csv
      - plots/cox_aft.pdf
      - plots/cox_aft_dummies.pdf
      - plots/cox_qq.pdf
      - plots/cox_summary.csv
    params:
      - afr.yaml:
        - covariates
        - weibull
        - log_logistic
        - log_normal
        # - gamma
        # - exponential
        - cox
    metrics:
      - plots/aft_comparison.csv
    outs:
      - plots/aft_comparison.tex
  copy_results:
      cmd: mkdir -p ~/ml_afr/plots &&  cp -r plots/* ~/ml_afr/plots/
      deps:
        - plots/