stages:
  set_config_paths:
      cmd: >
        echo "export DECKARD_CONFIG_DIR=./config" > .deckard_rc &&
        echo "export DECKARD_DEFAULT_CONFIG_FILE=torch_default.yaml" >> .deckard_rc &&
        source .deckard_rc
      outs: 
        - .deckard_rc
      deps:
        - ../config/default.yaml
      params:
        - ../config/default.yaml:
  simple_example:
      cmd: deckard && echo "Deckard ran successfully!" > deckard.log
      outs:
        - deckard.log
      deps:
        - .deckard_rc # Here to ensure config paths are set before running deckard
        - ../../deckard/__main__.py
  generate_data:
      foreach:
        - torch_mnist
        - torch_cifar10
      do:
        cmd: >
          deckard
          data=${item} 
          ~model
          ~attack
          files.model_file=null
          files.attack_file=null
          experiment_name=${item}
        outs:
          - output/data/${item}.pkl
        metrics:
          - output/scores/${item}.json
        deps:
          - .deckard_rc
          - ../../deckard/data/pytorch.py
        params:
          - ../config/data/${item}.yaml:
          ################################################
          #            Command Explanation:             #
          ################################################
          # deckard  data <-- Calls the deckard CLI tool for the DataConfig object.
          # data=${item}  <-- Specifies the dataset to be used in this iteration. See ../config/data/ for available datasets.
          # ~model  <-- Skips the model configuration for this run.
          # ~attack  <-- Skips the attack configuration for this run.
          # ~files.model_file  <-- Skips the model file specification.
          # ~files.attack_file  <-- Skips the attack file specification.
          ################################################
  train:
    foreach:
      - {data: torch_mnist, num_channels: 1, num_classes: 10}
      - {data: torch_cifar10, num_channels: 3, num_classes: 10}
    do:
      cmd: >
        deckard 
        data=${item.data} 
        model=torch_resnet18
        ~attack
        files.attack_file=null
        experiment_name=${item.data}_resnet18_training
        ++model.model_params.num_channels=${item.num_channels}
        ++model.model_params.num_classes=${item.num_classes}
      outs:
        - output/models/${item.data}_resnet18_training.pkl
      deps:
        - .deckard_rc
        - ../../deckard/data/pytorch.py
        - ../../deckard/model/pytorch.py
      metrics:
        - output/scores/${item.data}_resnet18_training.json
      params:
        - ../config/data/${item.data}.yaml:
        - ../config/model/torch_resnet18.yaml:
        ################################################
        #            Command Explanation:             #
        ################################################
        # deckard  <-- Calls the deckard CLI tool
        # data=${item.data}  <-- Specifies the dataset to be used in this iteration.
        # model=torch_resnet18  <-- Specifies the model architecture to be used.
        # ++model.num_channels=${item.num_channels}  <-- Sets the number of input channels
        # ++model.num_classes=${item.num_classes}  <-- Sets the number of output classes
        # +files.data_file=data/${item.data}.pkl <-- Specifies the input data file
        # +files.model_file=models/${item.data}_resnet18.pkl <-- Specifies the output model file
        ################################################
  # defend:
  #   matrix:
  #     data: [{name : torch_mnist, num_channels: 1, num_classes: 10}, {name : torch_cifar10, num_channels: 3, num_classes: 10}]
      