_target_: deckard.model.PytorchModelConfig
name: torch_example.ResNet18
model_params:
  num_channels: 1
fit_params:
  nb_epochs: 1
  batch_size: 1024
criterion:
    name : torch.nn.CrossEntropyLoss
optimizer:
    name : torch.optim.SGD
    lr : 0.01
    momentum : 0.9
clip_values : [0, 255]
defenses:
  - name: art.defences.preprocessor.FeatureSqueezing 
    bit_depth: 32
    clip_values: [0, 255]
