stages:
  set_config_paths:
      cmd: >
        echo "export DECKARD_CONFIG_DIR=../../config" > .deckard_rc &&
        echo "export DECKARD_DEFAULT_CONFIG_FILE=default.yaml" >> .deckard_rc &&
        source .deckard_rc
      outs: 
        - .deckard_rc
      deps:
        - ../../config/default.yaml
      params:
        - ../../config/default.yaml:
  simple_example:
      cmd: deckard experiment_name=default && echo "Deckard ran successfully!" > deckard.log
      outs:
        - deckard.log
      deps:
        - .deckard_rc # Here to ensure config paths are set before running deckard
        - ../../../deckard
  generate_data:
      foreach:
        - adult
        - classification
        - diabetes
        - digits
        - regression
        - kdd_nsl
        - ddos
        - sms_spam
        - truthseeker
      do:
        cmd: >
          deckard 
          data=${item} 
          +files.data_file=outputs/data/${item}.pkl 
          +files.score_file=outputs/scores/data/${item}.json
          experiment_name=${item}
          ~model 
          ~attack
          ~directions
          ~optimizers
        outs:
          - outputs/data/${item}.pkl
        metrics:
          - outputs/scores/data/${item}.json
        deps:
          - .deckard_rc
          - ../../../deckard/data/
        params:
          - ../../config/data/${item}.yaml:
          ################################################
          #            Command Explanation:             #
          ################################################
          # deckard  <-- Calls the deckard CLI tool
          # data=${item}  <-- Specifies the dataset to be used in this iteration. See ../../config/data/ for available datasets.
          # +files.data_file=data/${item}.pkl <-- Specifies the output path for the generated data file.
          # +files.score_file=scores/${item}.json <-- Specifies the output path for the score file.
          # ~model <-- Drops default model configuration.
          # ~attack <-- Drops default attack configuration.
          ################################################
  train_rf:
      foreach:
        - adult
        - classification
        - digits
      do:
        cmd: >
          deckard 
          data=${item} 
          +files.data_file=outputs/data/${item}.pkl 
          +files.model_file=outputs/models/${item}/rf.pkl
          +files.score_file=outputs/scores/models/${item}/rf.json
          experiment_name=${item}_rf
          model=rf.yaml 
          ~attack
          ~directions
          ~optimizers
        outs:
          - outputs/models/${item}/rf.pkl
        metrics:
          - outputs/scores/models/${item}/rf.json
        deps:
          - outputs/data/${item}.pkl
          - ../../../deckard/model
        params:
          - ../../config/model/rf.yaml:
          - ../../config/data/${item}.yaml:
          ################################################
          #            Command Explanation:             #
          ################################################
          # deckard  <-- Calls the deckard CLI tool
          # model=${item}  <-- Specifies the model to be trained for this iteration. See ../../config/model/ for available models.
          # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
          # +files.model_file=models/${item}/model.pkl <-- Specifies the output path for the trained model file.
          # +files.score_file=scores/models/${item}/model.json <-- Specifies the output path for the model score file.
          # model=rf.yaml  <-- Specifies the model configuration to be used.
          # ~attack <-- Drops default attack configuration.
  attack_rf:
    foreach:
      - adult
      - classification
      - digits
    do:
      cmd: >
        deckard 
        data=${item} 
        +files.data_file=outputs/data/${item}.pkl 
        +files.model_file=outputs/models/${item}/rf.pkl
        +files.score_file=outputs/scores/attacks/${item}/rf/hsj.json
        model=rf.yaml 
        attack=hsj.yaml
        experiment_name=${item}_rf_hsj
        ~directions
        ~optimizers
      metrics:
        - outputs/scores/attacks/${item}/rf/hsj.json
      deps:
        - outputs/data/${item}.pkl
        - outputs/models/${item}/rf.pkl
        - ../../../deckard/attack
      params:
        - ../../config/model/rf.yaml:
        - ../../config/attack/hsj.yaml:
        - ../../config/data/${item}.yaml:
        ################################################
        #            Command Explanation:             #
        ################################################
        # deckard  <-- Calls the deckard CLI tool
        # data=${item}  <-- Specifies the dataset to be used in this iteration. See ../../config/data/ for available datasets.
        # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
        # +files.model_file=models/${item}/model.pkl <-- Specifies the input trained model file
        # +files.score_file=scores/attacks/hsj/${item}_rf_attack.json <-- Specifies the output path for the attack score file.
        # model=rf.yaml  <-- Specifies the model configuration to be used.
  evade_rf:
    foreach:
      - adult
      # - classification
      # - digits
    do:
      cmd: >
        deckard 
        data=${item} 
        +files.data_file=outputs/data/${item}.pkl
        experiment_name="*"
        hydra.sweeper.study_name=evasion_${item}
        model=rf.yaml 
        --multirun
      deps:
        - outputs/data/${item}.pkl
        - ../../../deckard/model
      outs:
        - outputs/logs/evasion_${item}:
            cache: false
      params:
        - ../../config/model/rf.yaml:
        - ../../config/data/${item}.yaml:
        ################################################
        #            Command Explanation:             #
        ################################################
        # deckard  <-- Calls the deckard CLI tool
        # data=${item}  <-- Specifies the dataset to be used in this iteration. See ../../config/data/ for available datasets.
        # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
        # +files.score_file=scores/evade/${item}/{{hash}}.json <-- Specifies the output path for the evasion attack score file, where {{hash}} is replaced by the experiment hash.
        # experiment_name=${item}_rf_hsj  <-- Specifies the experiment name for logging and output organization.
        # hydra.sweeper.study_name=evasion_${item}  <-- Sets the Optuna study name for hyperparameter optimization.
        # model
  infer_membership_rf:
    foreach:
      - adult
      # - classification
      # - digits
    do:
      cmd: >
        deckard 
        data=${item} 
        +files.data_file=outputs/data/${item}.pkl 
        model=rf.yaml 
        attack=membership.yaml
        experiment_name="*"
        hydra.sweeper.study_name=membership_inference_${item}
        optimizers=["accuracy","membership_inference_accuracy"]
        directions=["maximize","minimize"]
        --multirun
      outs:
        - outputs/logs/membership_inference_${item}:
            cache: false
      deps:
        - outputs/data/${item}.pkl
        - ../../../deckard/attack
      params:
        - ../../config/model/rf.yaml:
        - ../../config/attack/membership.yaml:
        - ../../config/data/${item}.yaml:
        ################################################
        #            Command Explanation:             #
        ################################################
        # deckard  <-- Calls the deckard CLI tool
        # data=${item}  <-- Specifies the dataset to be used in this iteration. See ../../config/data/ for available datasets.
        # +files.data_file=data/${item}.pkl <-- Specifies the input data file path.
        # +files.model_file=models/${item}/model.pkl <-- Specifies the input trained model file
        # +files.score_file=scores/membership_inference/${item}_rf_membership_inference.json <-- Specifies the output path for the membership inference attack score file.
        # model=rf.yaml  <-- Specifies the model configuration to be used.