stages:
  prepare:
    cmd: python -m deckard.layers.runner prepare
    params:
      - data
      - files
    outs:
      - prepare/${files.data_file}
  train:
    cmd:  python  -m deckard.layers.runner train
    deps:
    - prepare/${files.data_file}
    params:
    - data
    - files
    - model
    - plots
    - scorers
    # outs:
    # metrics:
  # defend:
  #   cmd:  python  -m deckard.layers.defend --layer_name defend
  #   deps:
  #   - ${prepare.outputs.folder}/${prepare.outputs.file}
  #   - art_model/
  #   params:
  #   - defend.config
  #   - defend.inputs
  #   outs:
  #   - defend/:
  #       cache: true
  # attack:
  #   cmd:  python  -m deckard.layers.attack --layer_name attack
  #   deps:
  #   - ${prepare.outputs.folder}/${prepare.outputs.file}
  #   - defend
  #   params:
  #   - attack
  #   outs:
  #   - attack/:
  #       cache: true
