stages:
  prepare:
    cmd: python -m deckard.layers.prepare
    params:
      - prepare
    outs: 
      - prepare/data.pickle
  control:
    cmd:  python -m deckard.layers.art_model  --layer_name art_model
    deps:
    - prepare/data.pickle
    params:
    - art_model
    outs:
    - art_model/:
        cache: true
  defend:
    cmd:  python -m deckard.layers.defend --layer_name defend
    deps:
    - prepare/data.pickle
    - art_model/model
    - configs/defence_config.yaml
    params:
    - defend
    outs:
    - defend/:
        cache: true
  attack:
    cmd:  python -m deckard.layers.attack --layer_name attack
    deps:
    - prepare/data.pickle
    - defend/model
    - configs/attack_config.yaml
    params:
    - attack
    outs:
    - attack/:
        cache: true





