prepare:
  config:
    name: 'mnist'
    params:
      shuffle : True
      stratify : True
      random_state : 0
      test_size : 200
      train_size : 200
  outputs:
    folder : prepare
    file : data.pickle
    predictions :
    ground_truth :
  scores:
    file:
    folder:
    time_dict:
  plots:
    file:
    folder:
art_model:
  inputs:
    folder : "."
    data : prepare/data.pickle
    type : 'tf1'
    classifier : True
    is_fitted : True
    url: "https://www.dropbox.com/s/bv1xwjaf1ov4u7y/mnist_ratio%3D0.h5?dl=1"
  outputs:
    folder : "art_model"
    model : "model"
    params : "params.json"
    ground_truth : "ground_truth.json"
    predictions : "predictions.json"
  metrics:
    scores : "scores.json"
defend:
  inputs:
    folder : "."
    data : prepare/data.pickle
    type : 'tf1'
    classifier : True
    is_fitted : False
    model: art_model/model/
  config :
    name: art.defences.preprocessor.FeatureSqueezing
    params:
      'bit_depth' : 8
  outputs:
    folder : "defend"
    model : "model"
    params : "params.json"
    ground_truth : "ground_truth.json"
    predictions : "predictions.json"
  metrics:
    scores : "defend_scores.json"
attack:
  inputs:
    folder : "."
    data : prepare/data.pickle
    type : 'tf1'
    classifier : True
    is_fitted : True
    attack_size : 10
    model: defend/model
  config :
    name:  art.attacks.evasion.HopSkipJump
    params:
      max_iter : 5
      max_eval : 100
      init_eval : 100
      init_size : 100
  outputs:
    folder : "attack"
    model : "model"
    params : "params.json"
    ground_truth : "ground_truth.json"
    predictions : "predictions.json"
  metrics:
    scores : "scores.json"
evaluate:
  inputs:
    folder : train
    ground_truth : "predictions.json"
    predictions : 'ground_truth.json'
    classifier : True
    recursive : True
  config :
    name: sklearn.impute.SimpleImputer
    params:
      'strategy' : 'mean'
  outputs:
    folder : "evaluate"
    model : "model"
    params : "params.json"
  metrics:
    scores : "scores.json"
visualise:
  inputs:
    folder : "."
    data : prepare/data.pickle
    type : 'tf1'
    art : False
    classifier : True
    is_fitted : True
    model: defend/model
  config :
    name: sklearn.impute.SimpleImputer
    params:
      'strategy' : 'mean'
  outputs:
    folder : "."
  plots:
    roc_auc: "ROC_AUC.pdf"
