prepare: 
  name: 'mnist'
  params:
    shuffle : True 
    stratify : True
    random_state : 0
    train_size : .01
  data_file : "data.pkl"
  output_folder : "."
control:
  input_model : "https://www.dropbox.com/s/bv1xwjaf1ov4u7y/mnist_ratio%3D0.h5?dl=1"
  model_type : "tf1" 
  data_file : "data.pkl" 
  output_folder : "control"
  output_name : control_model.pb
defend:
  defence_config: "configs/defence_config.yaml"
  input_model : "control_model.pb" 
  input_folder : "control/" 
  model_type : "tf1" 
  data_file : "data.pkl" 
  output_folder : "defences/" 
  output_name : "defended_model"  
attack:
  attack_config: "configs/attack_config.yaml"
  input_model : "defended_model" 
  input_folder : "defences/" 
  model_type : "tf1" 
  data_file : "data.pkl" 
  output_folder : "attacks/" 
  output_name : "attacked_model"
  attack_size : 100
roc_auc:
  input_folder : control/
  ground_truth_file : "ground_truth.json"
  predictions_file : "predictions.json"
  layer_name : evaluate
  config : "configs/evaluate.yaml"