name: "Push Docs Check"
on:
  push:
    branches:
      - refactor-squashed

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: refactor-squashed
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name : install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[lifelines,anjana,torch,fairlearn,seaborn,yellowbrick,docs,test,datasets]'
    - name : build docs
      run: |
        cd docs
        make html
    - name: commit changes
      uses : stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update docs
        branch: refactor-squashed
        file_pattern: docs/build/html/** docs/notebooks/*.ipynb docs/notebooks/dvc.lock
        commit_options: '--no-verify --signoff'
        repository: .
        commit_user_name: github-actions
        commit_user_email: github-actions@users.noreply.github.com
        commit_author: github-actions
