name: Optional Lifelines Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  lifelines-tests:
    uses: ./.github/workflows/optional-dependency-test-reusable.yml
    with:
      workflow_name: lifelines
      extra: lifelines
      tests: test/test_layers/test_survival.py test/test_data/test_data.py -k lifelines
