name: Optional Fairlearn Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  fairlearn-tests:
    uses: ./.github/workflows/optional-dependency-test-reusable.yml
    with:
      workflow_name: fairlearn
      extra: fairlearn
      tests: test/test_data/test_data_fairness.py test/test_data/test_fairness.py test/test_model/test_model_fairness.py
