name: Optional Seaborn Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  seaborn-tests:
    uses: ./.github/workflows/optional-dependency-test-reusable.yml
    with:
      workflow_name: seaborn
      extra: seaborn
      tests: test/test_plot/test_seaborn.py
