name: Test Optional Dependencies (Matrix)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-optional-deps:
    name: optional-${{ matrix.dep_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - dep_name: fairlearn
            dep_group: fairlearn
            test_paths: test/test_plugins/test_fairlearn
          - dep_name: lifelines
            dep_group: lifelines
            test_paths: test/test_plugins/test_lifelines
          - dep_name: seaborn
            dep_group: seaborn
            test_paths: test/test_plugins/test_searborn/test_seaborn.py
          - dep_name: torch
            dep_group: torch
            test_paths: test/test_frameworks/test_pytorch test/test_attack/test_attack.py
          - dep_name: yellowbrick
            dep_group: "seaborn,yellowbrick"
            test_paths: test/test_plugins/test_yellowbrick/test_yellowbrick.py
          - dep_name: anjana
            dep_group: anjana
            test_paths: test/test_plugins/test_anjana
    uses: ./.github/workflows/optional-dependency-test-reusable.yml
    with:
      workflow_name: pr-${{ matrix.dep_name }}
      extra: ${{ matrix.dep_group }}
      tests: ${{ matrix.test_paths }}
